import { type ReactNode, createContext, useContext, useState } from "react";

export type Language =
  | "en"
  | "hi"
  | "ta"
  | "te"
  | "kn"
  | "ml"
  | "bn"
  | "mr"
  | "gu";

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    students: "Students",
    teachers: "Teachers",
    classes: "Classes",
    attendance: "Attendance",
    grades: "Grades",
    timetable: "Timetable",
    exams: "Exams",
    announcements: "Announcements",
    library: "Library",
    finance: "Finance",
    events: "Events",
    subjects: "Subjects",
    reports: "Reports",
    messages: "Messages",
    settings: "Settings",
    documents: "Documents",
    transport: "Transport",
    homework: "Homework",
    bulkImport: "Bulk Import",
    academicYear: "Academic Year",
    clubs: "Clubs & Societies",
    forums: "Discussion Forums",
    questionPaper: "Question Papers",
    analytics: "Analytics",
    auditLog: "Audit Log",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    search: "Search",
    close: "Close",
    submit: "Submit",
    download: "Download",
    upload: "Upload",
    all: "All",
    collegeStudents: "College Students",
    collegeFaculty: "College Faculty",
    parentPortal: "Parent Portal",
    school: "School",
    college: "College",
    general: "General",
    studentsPage: "Students Management",
    teachersPage: "Teachers Management",
    classesPage: "Classes Management",
    attendancePage: "Attendance Tracker",
    gradesPage: "Grades Management",
    timetablePage: "Timetable",
    examsPage: "Exams",
    announcementsPage: "Announcements",
    libraryPage: "Library",
    financePage: "Finance",
    eventsPage: "Events",
    subjectsPage: "Subjects",
    reportsPage: "Reports",
    messagesPage: "Messages",
    settingsPage: "Settings",
    documentsPage: "Documents",
    transportPage: "Transport Management",
    homeworkPage: "Homework",
    analyticsPage: "Analytics Dashboard",
    auditLogPage: "Audit Log",
    clubsPage: "Clubs & Societies",
    forumsPage: "Discussion Forums",
    addStudent: "Add Student",
    addTeacher: "Add Teacher",
    addClass: "Add Class",
    addEvent: "Add Event",
    addSubject: "Add Subject",
    markAttendance: "Mark Attendance",
    addGrade: "Add Grade",
    addExam: "Add Exam",
    addAnnouncement: "Add Announcement",
    compose: "Compose",
    inbox: "Inbox",
    sent: "Sent",
    starred: "Starred",
    trash: "Trash",
    present: "Present",
    absent: "Absent",
    pending: "Pending",
    paid: "Paid",
    unpaid: "Unpaid",
    payOnline: "Pay Online",
    viewDetails: "View Details",
    printReport: "Print Report",
    exportCSV: "Export CSV",
    name: "Name",
    class: "Class",
    section: "Section",
    subject: "Subject",
    date: "Date",
    status: "Status",
    actions: "Actions",
    total: "Total",
    fee: "Fee",
    amount: "Amount",
    type: "Type",
    description: "Description",
    phone: "Phone",
    email: "Email",
    address: "Address",
    gender: "Gender",
    male: "Male",
    female: "Female",
    role: "Role",
    password: "Password",
    confirm: "Confirm",
    update: "Update",
    profile: "Profile",
    logout: "Logout",
    login: "Login",
    signup: "Sign Up",
    welcome: "Welcome",
    loading: "Loading...",
    noData: "No data found",
    filter: "Filter",
    reset: "Reset",
    print: "Print",
    share: "Share",
    approve: "Approve",
    reject: "Reject",
    reserve: "Reserve",
    return: "Return",
    fine: "Fine",
    available: "Available",
    checkedOut: "Checked Out",
    reserved: "Reserved",
    overdue: "Overdue",
    totalClasses: "Total Classes",
    totalStudents: "Total Students",
    avgClassSize: "Avg Class Size",
    classTeacher: "Class Teacher",
    room: "Room",
    editClass: "Edit Class",
    addNewClass: "Add New Class",
    searchClasses: "Search classes...",
    noClassesFound: "No classes found",
    deleteClass: "Delete Class",
    activeClasses: "classes active",
    gradeName: "Grade / Class Name",
    numberOfStudents: "Number of Students",
    roomNumber: "Room Number",
    selectTeacher: "Select teacher",
    quickActions: "Quick Actions",
    studentEnrollmentTrend: "Student Enrollment Trend",
    monthlyPerformanceScore: "Monthly Performance Score",
    topStudents: "Top Students",
    recentActivity: "Recent Activity",
    attendanceOverview: "Attendance Overview",
    welcomeBack: "Welcome back! Here's your school overview.",
    rank: "Rank",
    average: "Average",
    viewAll: "View All",
    scheduleExam: "Schedule Exam",
    postAnnouncement: "Post Announcement",
    feeCollection: "Fee Collection",
    viewReports: "View Reports",
    myTimetable: "My Timetable",
    leaveApplication: "Leave Application",
    attendanceSummary: "Attendance Summary",
    reportCard: "Report Card",
    feeHistory: "Fee History",
    gpaCalculator: "GPA Calculator",
    digitalLibrary: "Digital Library",
    bookReservation: "Book Reservation",
    budgetReport: "Budget Report",
    paymentHistory: "Payment History",
    noResults: "No results found",
    language: "Language",
    backgroundColor: "Background Color",
    saveChanges: "Save Changes",
    profileSettings: "Profile Settings",
    security: "Security",
    notifications: "Notifications",
    schoolSettings: "School Settings",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    selectClass: "Select Class",
    selectDay: "Select Day",
    selectExam: "Select Exam",
    selectSubject: "Select Subject",
    period: "Period",
    saveAttendance: "Save Attendance",
    saveGrades: "Save Grades",
    attendanceRate: "Attendance Rate",
    studentName: "Student Name",
    rollNo: "Roll No.",
    age: "Age",
    department: "Department",
    qualification: "Qualification",
    contactNo: "Contact",
    totalTeachers: "Total Teachers",
    active: "Active",
    departments: "Departments",
    linkedAccounts: "Linked Accounts",
    notLinked: "Not Linked",
    examName: "Exam Name",
    maxMarks: "Max Marks",
    enterMarks: "Enter Marks",
    audience: "Audience",
    priorityLabel: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    addEventBtn: "Add Event",
    location: "Location",
    participants: "Participants",
    eventTitle: "Event Title",
    addEntry: "Add Entry",
    noEntriesFound: "No entries found",
    weeklySchedule: "Weekly Schedule",
    removeEntry: "Remove Entry",
    searchStudents: "Search students...",
    searchTeachers: "Search teachers...",
    searchExams: "Search exams...",
    searchEvents: "Search events...",
    searchBooks: "Search books...",
    returnBook: "Return",
    issuedBooks: "Issued Books",
    finesTab: "Fines",
    reservationsTab: "Reservations",
    physicalBooks: "Physical Books",
    digitalBooksTab: "Digital Library",
    uploadBook: "Upload Book",
    budgetOverview: "Budget Overview",
    income: "Income",
    expenses: "Expenses",
    balance: "Balance",
    feeReminder: "Fee Reminder",
    paymentMethod: "Payment Method",
    transactionHistory: "Transaction History",
    uploadFile: "Upload File",
    noDocuments: "No documents uploaded",
    routeName: "Route Name",
    driverName: "Driver",
    vehicle: "Vehicle",
    stops: "Stops",
    importData: "Import Data",
    exportData: "Export Data",
    startDate: "Start Date",
    endDate: "End Date",
    currentYear: "Current Year",
    forumTitle: "Forum Title",
    newPost: "New Post",
    lastActivity: "Last Activity",
    clubName: "Club Name",
    joinClub: "Join Club",
    requirements: "Requirements",
    questionTypeLabel: "Question Type",
    mcq: "MCQ",
    shortAnswer: "Short Answer",
    essayType: "Essay",
    addQuestion: "Add Question",
    assignedTo: "Assigned To",
    submittedBy: "Submitted By",
    gradeSubmission: "Grade",
    lessonTitle: "Lesson Title",
    objective: "Objective",
    exportCSVBtn: "Export CSV",
    scheduleNewExam: "Schedule New Exam",
    enterGrades: "Enter Grades",
    selectClassFirst: "Select a class to mark attendance",
    attendanceMark: "Mark",
    totalFees: "Total Fees",
    collected: "Collected",
    pendingFees: "Pending",
    payNow: "Pay Now",
    configureStripe: "Configure Stripe",
    uploadDate: "Upload Date",
    fileSize: "File Size",
    category: "Category",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    students: "छात्र",
    teachers: "शिक्षक",
    classes: "कक्षाएं",
    attendance: "उपस्थिति",
    grades: "ग्रेड",
    timetable: "समय सारणी",
    exams: "परीक्षाएं",
    announcements: "घोषणाएं",
    library: "पुस्तकालय",
    finance: "वित्त",
    events: "कार्यक्रम",
    subjects: "विषय",
    reports: "रिपोर्ट",
    messages: "संदेश",
    settings: "सेटिंग्स",
    documents: "दस्तावेज़",
    transport: "परिवहन",
    homework: "गृहकार्य",
    bulkImport: "बल्क इम्पोर्ट",
    academicYear: "शैक्षणिक वर्ष",
    clubs: "क्लब और समितियां",
    forums: "चर्चा मंच",
    questionPaper: "प्रश्न पत्र",
    analytics: "विश्लेषण",
    auditLog: "ऑडिट लॉग",
    add: "जोड़ें",
    edit: "संपादित करें",
    delete: "हटाएं",
    save: "सहेजें",
    cancel: "रद्द करें",
    search: "खोजें",
    close: "बंद करें",
    submit: "जमा करें",
    download: "डाउनलोड",
    upload: "अपलोड",
    all: "सभी",
    collegeStudents: "कॉलेज छात्र",
    collegeFaculty: "कॉलेज फैकल्टी",
    parentPortal: "अभिभावक पोर्टल",
    school: "स्कूल",
    college: "कॉलेज",
    general: "सामान्य",
    studentsPage: "छात्र प्रबंधन",
    teachersPage: "शिक्षक प्रबंधन",
    classesPage: "कक्षा प्रबंधन",
    attendancePage: "उपस्थिति ट्रैकर",
    gradesPage: "ग्रेड प्रबंधन",
    timetablePage: "समय सारणी",
    examsPage: "परीक्षाएं",
    announcementsPage: "घोषणाएं",
    libraryPage: "पुस्तकालय",
    financePage: "वित्त",
    eventsPage: "कार्यक्रम",
    subjectsPage: "विषय",
    reportsPage: "रिपोर्ट",
    messagesPage: "संदेश",
    settingsPage: "सेटिंग्स",
    documentsPage: "दस्तावेज़",
    transportPage: "परिवहन प्रबंधन",
    homeworkPage: "गृहकार्य",
    analyticsPage: "विश्लेषण डैशबोर्ड",
    auditLogPage: "ऑडिट लॉग",
    clubsPage: "क्लब और समितियां",
    forumsPage: "चर्चा मंच",
    addStudent: "छात्र जोड़ें",
    addTeacher: "शिक्षक जोड़ें",
    addClass: "कक्षा जोड़ें",
    addEvent: "कार्यक्रम जोड़ें",
    addSubject: "विषय जोड़ें",
    markAttendance: "उपस्थिति दर्ज करें",
    addGrade: "ग्रेड जोड़ें",
    addExam: "परीक्षा जोड़ें",
    addAnnouncement: "घोषणा जोड़ें",
    compose: "लिखें",
    inbox: "इनबॉक्स",
    sent: "भेजे गए",
    starred: "तारांकित",
    trash: "ट्रैश",
    present: "उपस्थित",
    absent: "अनुपस्थित",
    pending: "लंबित",
    paid: "भुगतान किया",
    unpaid: "अभुगतान",
    payOnline: "ऑनलाइन भुगतान",
    viewDetails: "विवरण देखें",
    printReport: "रिपोर्ट प्रिंट करें",
    exportCSV: "CSV निर्यात",
    name: "नाम",
    class: "कक्षा",
    section: "अनुभाग",
    subject: "विषय",
    date: "तारीख",
    status: "स्थिति",
    actions: "क्रियाएं",
    total: "कुल",
    fee: "शुल्क",
    amount: "राशि",
    type: "प्रकार",
    description: "विवरण",
    phone: "फोन",
    email: "ईमेल",
    address: "पता",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    role: "भूमिका",
    password: "पासवर्ड",
    confirm: "पुष्टि करें",
    update: "अपडेट",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    login: "लॉग इन",
    signup: "साइन अप",
    welcome: "स्वागत",
    loading: "लोड हो रहा है...",
    noData: "कोई डेटा नहीं मिला",
    filter: "फ़िल्टर",
    reset: "रीसेट",
    print: "प्रिंट",
    share: "शेयर",
    approve: "स्वीकृत करें",
    reject: "अस्वीकार",
    reserve: "आरक्षित करें",
    return: "वापस करें",
    fine: "जुर्माना",
    available: "उपलब्ध",
    checkedOut: "जारी किया",
    reserved: "आरक्षित",
    overdue: "अतिदेय",
    totalClasses: "कुल कक्षाएं",
    totalStudents: "कुल छात्र",
    avgClassSize: "औसत कक्षा आकार",
    classTeacher: "कक्षा शिक्षक",
    room: "कमरा",
    editClass: "कक्षा संपादित करें",
    addNewClass: "नई कक्षा जोड़ें",
    searchClasses: "कक्षाएं खोजें...",
    noClassesFound: "कोई कक्षा नहीं मिली",
    deleteClass: "कक्षा हटाएं",
    activeClasses: "कक्षाएं सक्रिय",
    gradeName: "ग्रेड / कक्षा का नाम",
    numberOfStudents: "छात्रों की संख्या",
    roomNumber: "कमरा नंबर",
    selectTeacher: "शिक्षक चुनें",
    quickActions: "त्वरित क्रियाएं",
    studentEnrollmentTrend: "छात्र नामांकन प्रवृत्ति",
    monthlyPerformanceScore: "मासिक प्रदर्शन स्कोर",
    topStudents: "शीर्ष छात्र",
    recentActivity: "हाल की गतिविधि",
    attendanceOverview: "उपस्थिति अवलोकन",
    welcomeBack: "वापसी पर स्वागत है! यहाँ आपका स्कूल अवलोकन है।",
    rank: "रैंक",
    average: "औसत",
    viewAll: "सभी देखें",
    scheduleExam: "परीक्षा निर्धारित करें",
    postAnnouncement: "घोषणा पोस्ट करें",
    feeCollection: "शुल्क संग्रह",
    viewReports: "रिपोर्ट देखें",
    myTimetable: "मेरा समय सारणी",
    leaveApplication: "अवकाश आवेदन",
    attendanceSummary: "उपस्थिति सारांश",
    reportCard: "रिपोर्ट कार्ड",
    feeHistory: "शुल्क इतिहास",
    gpaCalculator: "जीपीए कैलकुलेटर",
    digitalLibrary: "डिजिटल पुस्तकालय",
    bookReservation: "पुस्तक आरक्षण",
    budgetReport: "बजट रिपोर्ट",
    paymentHistory: "भुगतान इतिहास",
    noResults: "कोई परिणाम नहीं",
    language: "भाषा",
    backgroundColor: "पृष्ठभूमि रंग",
    saveChanges: "परिवर्तन सहेजें",
    profileSettings: "प्रोफाइल सेटिंग्स",
    security: "सुरक्षा",
    notifications: "सूचनाएं",
    schoolSettings: "स्कूल सेटिंग्स",
    monday: "सोमवार",
    tuesday: "मंगलवार",
    wednesday: "बुधवार",
    thursday: "गुरुवार",
    friday: "शुक्रवार",
    saturday: "शनिवार",
    sunday: "रविवार",
    selectClass: "कक्षा चुनें",
    selectDay: "दिन चुनें",
    selectExam: "परीक्षा चुनें",
    selectSubject: "विषय चुनें",
    period: "पीरियड",
    saveAttendance: "उपस्थिति सहेजें",
    saveGrades: "ग्रेड सहेजें",
    attendanceRate: "उपस्थिति दर",
    studentName: "छात्र का नाम",
    rollNo: "रोल नं.",
    age: "आयु",
    department: "विभाग",
    qualification: "योग्यता",
    contactNo: "संपर्क",
    totalTeachers: "कुल शिक्षक",
    active: "सक्रिय",
    departments: "विभाग",
    linkedAccounts: "लिंक्ड अकाउंट",
    notLinked: "लिंक नहीं",
    examName: "परीक्षा नाम",
    maxMarks: "अधिकतम अंक",
    enterMarks: "अंक दर्ज करें",
    audience: "दर्शक",
    priorityLabel: "प्राथमिकता",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    addEventBtn: "कार्यक्रम जोड़ें",
    location: "स्थान",
    participants: "प्रतिभागी",
    eventTitle: "कार्यक्रम शीर्षक",
    addEntry: "प्रविष्टि जोड़ें",
    noEntriesFound: "कोई प्रविष्टि नहीं",
    weeklySchedule: "साप्ताहिक कार्यक्रम",
    removeEntry: "प्रविष्टि हटाएं",
    searchStudents: "छात्र खोजें...",
    searchTeachers: "शिक्षक खोजें...",
    searchExams: "परीक्षा खोजें...",
    searchEvents: "कार्यक्रम खोजें...",
    searchBooks: "पुस्तक खोजें...",
    returnBook: "वापस करें",
    issuedBooks: "जारी पुस्तकें",
    finesTab: "जुर्माना",
    reservationsTab: "आरक्षण",
    physicalBooks: "भौतिक पुस्तकें",
    digitalBooksTab: "डिजिटल पुस्तकालय",
    uploadBook: "पुस्तक अपलोड",
    budgetOverview: "बजट अवलोकन",
    income: "आय",
    expenses: "व्यय",
    balance: "शेष",
    feeReminder: "फीस अनुस्मारक",
    paymentMethod: "भुगतान विधि",
    transactionHistory: "लेनदेन इतिहास",
    uploadFile: "फाइल अपलोड",
    noDocuments: "कोई दस्तावेज़ नहीं",
    routeName: "मार्ग नाम",
    driverName: "चालक",
    vehicle: "वाहन",
    stops: "स्टॉप",
    importData: "डेटा आयात",
    exportData: "डेटा निर्यात",
    startDate: "शुरू तिथि",
    endDate: "समाप्ति तिथि",
    currentYear: "वर्तमान वर्ष",
    forumTitle: "फोरम शीर्षक",
    newPost: "नई पोस्ट",
    lastActivity: "अंतिम गतिविधि",
    clubName: "क्लब नाम",
    joinClub: "क्लब ज्वाइन",
    requirements: "आवश्यकताएं",
    questionTypeLabel: "प्रश्न प्रकार",
    mcq: "MCQ",
    shortAnswer: "लघु उत्तर",
    essayType: "निबंध",
    addQuestion: "प्रश्न जोड़ें",
    assignedTo: "सौंपा गया",
    submittedBy: "जमा किया",
    gradeSubmission: "ग्रेड",
    lessonTitle: "पाठ शीर्षक",
    objective: "उद्देश्य",
    exportCSVBtn: "CSV निर्यात",
    scheduleNewExam: "नई परीक्षा",
    enterGrades: "ग्रेड दर्ज करें",
    selectClassFirst: "उपस्थिति के लिए कक्षा चुनें",
    attendanceMark: "अंकित करें",
    totalFees: "कुल फीस",
    collected: "एकत्र",
    pendingFees: "बकाया",
    payNow: "अभी भुगतान",
    configureStripe: "Stripe कॉन्फ़िगर",
    uploadDate: "अपलोड तारीख",
    fileSize: "फाइल आकार",
    category: "श्रेणी",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    students: "மாணவர்கள்",
    teachers: "ஆசிரியர்கள்",
    classes: "வகுப்புகள்",
    attendance: "வருகை",
    grades: "தரங்கள்",
    timetable: "நேர அட்டவணை",
    exams: "தேர்வுகள்",
    announcements: "அறிவிப்புகள்",
    library: "நூலகம்",
    finance: "நிதி",
    events: "நிகழ்வுகள்",
    subjects: "பாடங்கள்",
    reports: "அறிக்கைகள்",
    messages: "செய்திகள்",
    settings: "அமைப்புகள்",
    documents: "ஆவணங்கள்",
    transport: "போக்குவரத்து",
    homework: "வீட்டுப்பாடம்",
    bulkImport: "மொத்த இறக்குமதி",
    academicYear: "கல்வியாண்டு",
    clubs: "கழகங்கள்",
    forums: "விவாத மன்றங்கள்",
    questionPaper: "வினாத்தாள்",
    analytics: "பகுப்பாய்வு",
    auditLog: "தணிக்கை பதிவு",
    add: "சேர்",
    edit: "திருத்து",
    delete: "நீக்கு",
    save: "சேமி",
    cancel: "ரத்து",
    search: "தேடு",
    close: "மூடு",
    submit: "சமர்ப்பி",
    download: "பதிவிறக்கம்",
    upload: "பதிவேற்றம்",
    all: "அனைத்தும்",
    collegeStudents: "கல்லூரி மாணவர்கள்",
    collegeFaculty: "கல்லூரி ஆசிரியர்",
    parentPortal: "பெற்றோர் போர்டல்",
    school: "பள்ளி",
    college: "கல்லூரி",
    general: "பொது",
    studentsPage: "மாணவர் மேலாண்மை",
    teachersPage: "ஆசிரியர் மேலாண்மை",
    classesPage: "வகுப்பு மேலாண்மை",
    attendancePage: "வருகை கண்காணிப்பு",
    gradesPage: "தரங்கள் மேலாண்மை",
    timetablePage: "நேர அட்டவணை",
    examsPage: "தேர்வுகள்",
    announcementsPage: "அறிவிப்புகள்",
    libraryPage: "நூலகம்",
    financePage: "நிதி",
    eventsPage: "நிகழ்வுகள்",
    subjectsPage: "பாடங்கள்",
    reportsPage: "அறிக்கைகள்",
    messagesPage: "செய்திகள்",
    settingsPage: "அமைப்புகள்",
    documentsPage: "ஆவணங்கள்",
    transportPage: "போக்குவரத்து மேலாண்மை",
    homeworkPage: "வீட்டுப்பாடம்",
    analyticsPage: "பகுப்பாய்வு டாஷ்போர்டு",
    auditLogPage: "தணிக்கை பதிவு",
    clubsPage: "கழகங்கள்",
    forumsPage: "விவாத மன்றங்கள்",
    addStudent: "மாணவரை சேர்",
    addTeacher: "ஆசிரியரை சேர்",
    addClass: "வகுப்பை சேர்",
    addEvent: "நிகழ்வை சேர்",
    addSubject: "பாடத்தை சேர்",
    markAttendance: "வருகை குறி",
    addGrade: "தரம் சேர்",
    addExam: "தேர்வு சேர்",
    addAnnouncement: "அறிவிப்பு சேர்",
    compose: "எழுது",
    inbox: "இன்பாக்ஸ்",
    sent: "அனுப்பியது",
    starred: "நட்சத்திரமிட்டது",
    trash: "குப்பை",
    present: "வருகை",
    absent: "வராத",
    pending: "நிலுவை",
    paid: "செலுத்தியது",
    unpaid: "செலுத்தாதது",
    payOnline: "ஆன்லைன் பணம்",
    viewDetails: "விவரங்கள்",
    printReport: "அறிக்கை அச்சு",
    exportCSV: "CSV ஏற்றுமதி",
    name: "பெயர்",
    class: "வகுப்பு",
    section: "பிரிவு",
    subject: "பாடம்",
    date: "தேதி",
    status: "நிலை",
    actions: "செயல்கள்",
    total: "மொத்தம்",
    fee: "கட்டணம்",
    amount: "தொகை",
    type: "வகை",
    description: "விளக்கம்",
    phone: "தொலைபேசி",
    email: "மின்னஞ்சல்",
    address: "முகவரி",
    gender: "பால்",
    male: "ஆண்",
    female: "பெண்",
    role: "பங்கு",
    password: "கடவுச்சொல்",
    confirm: "உறுதிப்படுத்து",
    update: "புதுப்பி",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    login: "உள்நுழை",
    signup: "பதிவு",
    welcome: "வரவேற்கிறோம்",
    loading: "ஏற்றுகிறது...",
    noData: "தரவு இல்லை",
    filter: "வடிகட்டு",
    reset: "மீட்டமை",
    print: "அச்சு",
    share: "பகிர்",
    approve: "அனுமதி",
    reject: "நிராகரி",
    reserve: "ஒதுக்கு",
    return: "திரும்ப",
    fine: "அபராதம்",
    available: "கிடைக்கும்",
    checkedOut: "வெளியேடுத்தது",
    reserved: "ஒதுக்கீடு",
    overdue: "தாமதம்",
    totalClasses: "மொத்த வகுப்புகள்",
    totalStudents: "மொத்த மாணவர்கள்",
    avgClassSize: "சராசரி வகுப்பு அளவு",
    classTeacher: "வகுப்பு ஆசிரியர்",
    room: "அறை",
    editClass: "வகுப்பு திருத்து",
    addNewClass: "புதிய வகுப்பு சேர்",
    searchClasses: "வகுப்புகள் தேடு...",
    noClassesFound: "வகுப்புகள் இல்லை",
    deleteClass: "வகுப்பு நீக்கு",
    activeClasses: "வகுப்புகள் செயல்பாட்டில்",
    gradeName: "தர/வகுப்பு பெயர்",
    numberOfStudents: "மாணவர் எண்ணிக்கை",
    roomNumber: "அறை எண்",
    selectTeacher: "ஆசிரியர் தேர்ந்தெடு",
    quickActions: "விரைவு செயல்கள்",
    studentEnrollmentTrend: "மாணவர் சேர்க்கை போக்கு",
    monthlyPerformanceScore: "மாதாந்திர செயல்திறன் மதிப்பெண்",
    topStudents: "சிறந்த மாணவர்கள்",
    recentActivity: "சமீபத்திய செயல்பாடு",
    attendanceOverview: "வருகை கண்ணோட்டம்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்! இங்கே உங்கள் பள்ளி கண்ணோட்டம்.",
    rank: "தரவரிசை",
    average: "சராசரி",
    viewAll: "அனைத்தும் பார்",
    scheduleExam: "தேர்வு அட்டவணை",
    postAnnouncement: "அறிவிப்பு இடு",
    feeCollection: "கட்டண சேகரிப்பு",
    viewReports: "அறிக்கைகள் பார்",
    myTimetable: "என் நேர அட்டவணை",
    leaveApplication: "விடுப்பு விண்ணப்பம்",
    attendanceSummary: "வருகை சுருக்கம்",
    reportCard: "மதிப்பெண் அட்டை",
    feeHistory: "கட்டண வரலாறு",
    gpaCalculator: "GPA கணிப்பாளர்",
    digitalLibrary: "டிஜிட்டல் நூலகம்",
    bookReservation: "புத்தக முன்பதிவு",
    budgetReport: "பட்ஜெட் அறிக்கை",
    paymentHistory: "கட்டண வரலாறு",
    noResults: "முடிவுகள் இல்லை",
    language: "மொழி",
    backgroundColor: "பின்னணி நிறம்",
    saveChanges: "மாற்றங்களை சேமி",
    profileSettings: "சுயவிவர அமைப்புகள்",
    security: "பாதுகாப்பு",
    notifications: "அறிவிப்புகள்",
    schoolSettings: "பள்ளி அமைப்புகள்",
    monday: "திங்கள்",
    tuesday: "செவ்வாய்",
    wednesday: "புதன்",
    thursday: "வியாழன்",
    friday: "வெள்ளி",
    saturday: "சனி",
    sunday: "ஞாயிறு",
    selectClass: "வகுப்பு தேர்ந்தெடு",
    selectDay: "நாள் தேர்ந்தெடு",
    selectExam: "தேர்வு தேர்ந்தெடு",
    selectSubject: "பாடம் தேர்ந்தெடு",
    period: "காலம்",
    saveAttendance: "வருகை சேமி",
    saveGrades: "தரங்கள் சேமி",
    attendanceRate: "வருகை விகிதம்",
    studentName: "மாணவர் பெயர்",
    rollNo: "சேர்க்கை எண்",
    age: "வயது",
    department: "துறை",
    qualification: "தகுதி",
    contactNo: "தொடர்பு",
    totalTeachers: "மொத்த ஆசிரியர்கள்",
    active: "செயலில்",
    departments: "துறைகள்",
    linkedAccounts: "இணைக்கப்பட்ட கணக்குகள்",
    notLinked: "இணைக்கப்படவில்லை",
    examName: "தேர்வு பெயர்",
    maxMarks: "அதிகபட்ச மதிப்பெண்",
    enterMarks: "மதிப்பெண் உள்ளிடு",
    audience: "பார்வையாளர்",
    priorityLabel: "முன்னுரிமை",
    high: "உயர்",
    medium: "நடுத்தர",
    low: "குறைந்த",
    addEventBtn: "நிகழ்வு சேர்",
    location: "இடம்",
    participants: "பங்கேற்பாளர்கள்",
    eventTitle: "நிகழ்வு தலைப்பு",
    addEntry: "பதிவு சேர்",
    noEntriesFound: "பதிவுகள் இல்லை",
    weeklySchedule: "வாராந்திர அட்டவணை",
    removeEntry: "பதிவு நீக்கு",
    searchStudents: "மாணவர் தேடு...",
    searchTeachers: "ஆசிரியர் தேடு...",
    searchExams: "தேர்வு தேடு...",
    searchEvents: "நிகழ்வு தேடு...",
    searchBooks: "புத்தகம் தேடு...",
    returnBook: "திரும்பு",
    issuedBooks: "வழங்கப்பட்ட புத்தகங்கள்",
    finesTab: "அபராதம்",
    reservationsTab: "ஒதுக்கீடு",
    physicalBooks: "அச்சு புத்தகங்கள்",
    digitalBooksTab: "டிஜிட்டல் நூலகம்",
    uploadBook: "புத்தகம் ஏற்று",
    budgetOverview: "பட்ஜெட் கண்ணோட்டம்",
    income: "வருமானம்",
    expenses: "செலவுகள்",
    balance: "இருப்பு",
    feeReminder: "கட்டண நினைவூட்டல்",
    paymentMethod: "கட்டண முறை",
    transactionHistory: "பரிவர்த்தனை வரலாறு",
    uploadFile: "கோப்பு ஏற்று",
    noDocuments: "ஆவணங்கள் இல்லை",
    routeName: "பாதை பெயர்",
    driverName: "ஓட்டுநர்",
    vehicle: "வாகனம்",
    stops: "நிறுத்தங்கள்",
    importData: "தரவு இறக்கு",
    exportData: "தரவு ஏற்று",
    startDate: "தொடக்க தேதி",
    endDate: "முடிவு தேதி",
    currentYear: "நடப்பு ஆண்டு",
    forumTitle: "மன்ற தலைப்பு",
    newPost: "புதிய இடுகை",
    lastActivity: "கடைசி செயல்பாடு",
    clubName: "கழக பெயர்",
    joinClub: "கழகம் சேர்",
    requirements: "தேவைகள்",
    questionTypeLabel: "கேள்வி வகை",
    mcq: "MCQ",
    shortAnswer: "குறுகிய பதில்",
    essayType: "கட்டுரை",
    addQuestion: "கேள்வி சேர்",
    assignedTo: "ஒதுக்கப்பட்டது",
    submittedBy: "சமர்ப்பிக்கப்பட்டது",
    gradeSubmission: "தரம்",
    lessonTitle: "பாட தலைப்பு",
    objective: "நோக்கம்",
    exportCSVBtn: "CSV ஏற்று",
    scheduleNewExam: "புதிய தேர்வு",
    enterGrades: "தரங்கள் உள்ளிடு",
    selectClassFirst: "வருகைக்கு வகுப்பு தேர்ந்தெடு",
    attendanceMark: "குறி",
    totalFees: "மொத்த கட்டணம்",
    collected: "சேகரிக்கப்பட்டது",
    pendingFees: "நிலுவை",
    payNow: "இப்போது செலுத்து",
    configureStripe: "Stripe அமை",
    uploadDate: "ஏற்று தேதி",
    fileSize: "கோப்பு அளவு",
    category: "வகை",
  },
  te: {
    dashboard: "డాష్‌బోర్డ్",
    students: "విద్యార్థులు",
    teachers: "ఉపాధ్యాయులు",
    classes: "తరగతులు",
    attendance: "హాజరు",
    grades: "గ్రేడ్లు",
    timetable: "సమయపట్టిక",
    exams: "పరీక్షలు",
    announcements: "ప్రకటనలు",
    library: "గ్రంథాలయం",
    finance: "ఆర్థికం",
    events: "కార్యక్రమాలు",
    subjects: "విషయాలు",
    reports: "నివేదికలు",
    messages: "సందేశాలు",
    settings: "సెట్టింగులు",
    documents: "పత్రాలు",
    transport: "రవాణా",
    homework: "గృహపాఠం",
    bulkImport: "బల్క్ దిగుమతి",
    academicYear: "విద్యా సంవత్సరం",
    clubs: "క్లబ్బులు",
    forums: "చర్చా వేదికలు",
    questionPaper: "ప్రశ్నపత్రం",
    analytics: "విశ్లేషణ",
    auditLog: "ఆడిట్ లాగ్",
    add: "జోడించు",
    edit: "సవరించు",
    delete: "తొలగించు",
    save: "సేవ్",
    cancel: "రద్దు",
    search: "వెతుకు",
    close: "మూసివేయి",
    submit: "సమర్పించు",
    download: "డౌన్‌లోడ్",
    upload: "అప్‌లోడ్",
    all: "అన్నీ",
    collegeStudents: "కళాశాల విద్యార్థులు",
    collegeFaculty: "కళాశాల అధ్యాపకులు",
    parentPortal: "తల్లిదండ్రుల పోర్టల్",
    school: "పాఠశాల",
    college: "కళాశాల",
    general: "సాధారణ",
    studentsPage: "విద్యార్థుల నిర్వహణ",
    teachersPage: "ఉపాధ్యాయుల నిర్వహణ",
    classesPage: "తరగతుల నిర్వహణ",
    attendancePage: "హాజరు ట్రాకర్",
    gradesPage: "గ్రేడ్ నిర్వహణ",
    timetablePage: "సమయపట్టిక",
    examsPage: "పరీక్షలు",
    announcementsPage: "ప్రకటనలు",
    libraryPage: "గ్రంథాలయం",
    financePage: "ఆర్థికం",
    eventsPage: "కార్యక్రమాలు",
    subjectsPage: "విషయాలు",
    reportsPage: "నివేదికలు",
    messagesPage: "సందేశాలు",
    settingsPage: "సెట్టింగులు",
    documentsPage: "పత్రాలు",
    transportPage: "రవాణా నిర్వహణ",
    homeworkPage: "గృహపాఠం",
    analyticsPage: "విశ్లేషణ డాష్‌బోర్డ్",
    auditLogPage: "ఆడిట్ లాగ్",
    clubsPage: "క్లబ్బులు",
    forumsPage: "చర్చా వేదికలు",
    addStudent: "విద్యార్థిని జోడించు",
    addTeacher: "ఉపాధ్యాయుని జోడించు",
    addClass: "తరగతి జోడించు",
    addEvent: "కార్యక్రమం జోడించు",
    addSubject: "విషయం జోడించు",
    markAttendance: "హాజరు గుర్తించు",
    addGrade: "గ్రేడ్ జోడించు",
    addExam: "పరీక్ష జోడించు",
    addAnnouncement: "ప్రకటన జోడించు",
    compose: "రాయి",
    inbox: "ఇన్‌బాక్స్",
    sent: "పంపిన",
    starred: "నక్షత్రం",
    trash: "చెత్త",
    present: "హాజరు",
    absent: "గైర్హాజరు",
    pending: "పెండింగ్",
    paid: "చెల్లించారు",
    unpaid: "చెల్లించలేదు",
    payOnline: "ఆన్‌లైన్ చెల్లింపు",
    viewDetails: "వివరాలు",
    printReport: "నివేదిక ముద్రించు",
    exportCSV: "CSV ఎగుమతి",
    name: "పేరు",
    class: "తరగతి",
    section: "విభాగం",
    subject: "విషయం",
    date: "తేదీ",
    status: "స్థితి",
    actions: "చర్యలు",
    total: "మొత్తం",
    fee: "రుసుము",
    amount: "మొత్తం",
    type: "రకం",
    description: "వివరణ",
    phone: "ఫోన్",
    email: "ఇమెయిల్",
    address: "చిరునామా",
    gender: "లింగం",
    male: "పురుష",
    female: "స్త్రీ",
    role: "పాత్ర",
    password: "పాస్‌వర్డ్",
    confirm: "నిర్ధారించు",
    update: "నవీకరించు",
    profile: "ప్రొఫైల్",
    logout: "లాగ్ అవుట్",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    welcome: "స్వాగతం",
    loading: "లోడ్ అవుతోంది...",
    noData: "డేటా లేదు",
    filter: "వడపోత",
    reset: "రీసెట్",
    print: "ముద్రించు",
    share: "భాగస్వామ్యం",
    approve: "ఆమోదించు",
    reject: "తిరస్కరించు",
    reserve: "రిజర్వ్",
    return: "తిరిగి ఇవ్వు",
    fine: "జరిమానా",
    available: "అందుబాటులో",
    checkedOut: "తీసుకెళ్ళారు",
    reserved: "రిజర్వ్ అయింది",
    overdue: "గడువు మించింది",
    totalClasses: "మొత్తం తరగతులు",
    totalStudents: "మొత్తం విద్యార్థులు",
    avgClassSize: "సగటు తరగతి పరిమాణం",
    classTeacher: "తరగతి ఉపాధ్యాయుడు",
    room: "గది",
    editClass: "తరగతి సవరించు",
    addNewClass: "కొత్త తరగతి జోడించు",
    searchClasses: "తరగతులు వెతుకు...",
    noClassesFound: "తరగతులు కనుగొనబడలేదు",
    deleteClass: "తరగతి తొలగించు",
    activeClasses: "తరగతులు చురుకుగా ఉన్నాయి",
    gradeName: "గ్రేడ్/తరగతి పేరు",
    numberOfStudents: "విద్యార్థుల సంఖ్య",
    roomNumber: "గది నంబర్",
    selectTeacher: "ఉపాధ్యాయుడిని ఎంచుకోండి",
    quickActions: "త్వరిత చర్యలు",
    studentEnrollmentTrend: "విద్యార్థుల నమోదు ధోరణి",
    monthlyPerformanceScore: "నెలవారీ పనితీరు స్కోర్",
    topStudents: "అగ్ర విద్యార్థులు",
    recentActivity: "ఇటీవలి కార్యకలాపం",
    attendanceOverview: "హాజరు అవలోకనం",
    welcomeBack: "తిరిగి స్వాగతం! ఇక్కడ మీ పాఠశాల అవలోకనం ఉంది.",
    rank: "ర్యాంక్",
    average: "సగటు",
    viewAll: "అన్నీ చూడు",
    scheduleExam: "పరీక్ష షెడ్యూల్",
    postAnnouncement: "ప్రకటన పోస్ట్",
    feeCollection: "రుసుము సేకరణ",
    viewReports: "నివేదికలు చూడు",
    myTimetable: "నా సమయపట్టిక",
    leaveApplication: "సెలవు దరఖాస్తు",
    attendanceSummary: "హాజరు సారాంశం",
    reportCard: "రిపోర్ట్ కార్డ్",
    feeHistory: "రుసుము చరిత్ర",
    gpaCalculator: "GPA కాల్క్యులేటర్",
    digitalLibrary: "డిజిటల్ గ్రంథాలయం",
    bookReservation: "పుస్తక రిజర్వేషన్",
    budgetReport: "బడ్జెట్ నివేదిక",
    paymentHistory: "చెల్లింపు చరిత్ర",
    noResults: "ఫలితాలు లేవు",
    language: "భాష",
    backgroundColor: "నేపథ్య రంగు",
    saveChanges: "మార్పులు సేవ్ చేయి",
    profileSettings: "ప్రొఫైల్ సెట్టింగులు",
    security: "భద్రత",
    notifications: "నోటిఫికేషన్లు",
    schoolSettings: "పాఠశాల సెట్టింగులు",
    monday: "సోమవారం",
    tuesday: "మంగళవారం",
    wednesday: "బుధవారం",
    thursday: "గురువారం",
    friday: "శుక్రవారం",
    saturday: "శనివారం",
    sunday: "ఆదివారం",
    selectClass: "తరగతి ఎంచుకో",
    selectDay: "రోజు ఎంచుకో",
    selectExam: "పరీక్ష ఎంచుకో",
    selectSubject: "విషయం ఎంచుకో",
    period: "కాలం",
    saveAttendance: "హాజరు సేవ్ చేయి",
    saveGrades: "గ్రేడ్‌లు సేవ్ చేయి",
    attendanceRate: "హాజరు రేటు",
    studentName: "విద్యార్థి పేరు",
    rollNo: "రోల్ నం.",
    age: "వయస్సు",
    department: "విభాగం",
    qualification: "అర్హత",
    contactNo: "సంప్రదింపు",
    totalTeachers: "మొత్తం ఉపాధ్యాయులు",
    active: "క్రియాశీలం",
    departments: "విభాగాలు",
    linkedAccounts: "అనుసంధానిత ఖాతాలు",
    notLinked: "అనుసంధానించబడలేదు",
    examName: "పరీక్ష పేరు",
    maxMarks: "గరిష్ట మార్కులు",
    enterMarks: "మార్కులు నమోదు",
    audience: "ప్రేక్షకులు",
    priorityLabel: "ప్రాధాన్యత",
    high: "అధిక",
    medium: "మధ్యస్థ",
    low: "తక్కువ",
    addEventBtn: "ఈవెంట్ జోడించు",
    location: "స్థానం",
    participants: "పాల్గొనేవారు",
    eventTitle: "ఈవెంట్ శీర్షిక",
    addEntry: "ఎంట్రీ జోడించు",
    noEntriesFound: "ఎంట్రీలు లేవు",
    weeklySchedule: "వారపు సమయసూచిక",
    removeEntry: "ఎంట్రీ తొలగించు",
    searchStudents: "విద్యార్థులను వెతకండి...",
    searchTeachers: "ఉపాధ్యాయులను వెతకండి...",
    searchExams: "పరీక్షలు వెతకండి...",
    searchEvents: "ఈవెంట్‌లు వెతకండి...",
    searchBooks: "పుస్తకాలు వెతకండి...",
    returnBook: "తిరిగి ఇవ్వు",
    issuedBooks: "జారీ చేసిన పుస్తకాలు",
    finesTab: "జరిమానా",
    reservationsTab: "రిజర్వేషన్లు",
    physicalBooks: "భౌతిక పుస్తకాలు",
    digitalBooksTab: "డిజిటల్ లైబ్రరీ",
    uploadBook: "పుస్తకం అప్‌లోడ్",
    budgetOverview: "బడ్జెట్ సమీక్ష",
    income: "ఆదాయం",
    expenses: "వ్యయాలు",
    balance: "నిల్వ",
    feeReminder: "ఫీజు రిమైండర్",
    paymentMethod: "చెల్లింపు పద్ధతి",
    transactionHistory: "లావాదేవీ చరిత్ర",
    uploadFile: "ఫైల్ అప్‌లోడ్",
    noDocuments: "పత్రాలు లేవు",
    routeName: "మార్గం పేరు",
    driverName: "డ్రైవర్",
    vehicle: "వాహనం",
    stops: "స్టాప్‌లు",
    importData: "డేటా దిగుమతి",
    exportData: "డేటా ఎగుమతి",
    startDate: "ప్రారంభ తేదీ",
    endDate: "ముగింపు తేదీ",
    currentYear: "ప్రస్తుత సంవత్సరం",
    forumTitle: "ఫోరమ్ శీర్షిక",
    newPost: "కొత్త పోస్ట్",
    lastActivity: "చివరి కార్యకలాపం",
    clubName: "క్లబ్ పేరు",
    joinClub: "క్లబ్ చేరు",
    requirements: "అవసరాలు",
    questionTypeLabel: "ప్రశ్న రకం",
    mcq: "MCQ",
    shortAnswer: "సంక్షిప్త సమాధానం",
    essayType: "వ్యాసం",
    addQuestion: "ప్రశ్న జోడించు",
    assignedTo: "అప్పగించబడింది",
    submittedBy: "సమర్పించినవారు",
    gradeSubmission: "గ్రేడ్",
    lessonTitle: "పాఠం శీర్షిక",
    objective: "లక్ష్యం",
    exportCSVBtn: "CSV ఎగుమతి",
    scheduleNewExam: "కొత్త పరీక్ష",
    enterGrades: "గ్రేడ్‌లు నమోదు చేయి",
    selectClassFirst: "హాజరు కోసం తరగతి ఎంచుకో",
    attendanceMark: "గుర్తు",
    totalFees: "మొత్తం ఫీజు",
    collected: "సేకరించారు",
    pendingFees: "పెండింగ్",
    payNow: "ఇప్పుడు చెల్లించు",
    configureStripe: "Stripe కాన్ఫిగర్",
    uploadDate: "అప్‌లోడ్ తేదీ",
    fileSize: "ఫైల్ పరిమాణం",
    category: "వర్గం",
  },
  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    students: "ವಿದ್ಯಾರ್ಥಿಗಳು",
    teachers: "ಶಿಕ್ಷಕರು",
    classes: "ತರಗತಿಗಳು",
    attendance: "ಹಾಜರಾತಿ",
    grades: "ಶ್ರೇಣಿಗಳು",
    timetable: "ಸಮಯ ಪಟ್ಟಿ",
    exams: "ಪರೀಕ್ಷೆಗಳು",
    announcements: "ಪ್ರಕಟಣೆಗಳು",
    library: "ಗ್ರಂಥಾಲಯ",
    finance: "ಹಣಕಾಸು",
    events: "ಕಾರ್ಯಕ್ರಮಗಳು",
    subjects: "ವಿಷಯಗಳು",
    reports: "ವರದಿಗಳು",
    messages: "ಸಂದೇಶಗಳು",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    documents: "ದಾಖಲೆಗಳು",
    transport: "ಸಾರಿಗೆ",
    homework: "ಗೃಹಕಾರ್ಯ",
    bulkImport: "ಬಲ್ಕ್ ಆಮದು",
    academicYear: "ಶೈಕ್ಷಣಿಕ ವರ್ಷ",
    clubs: "ಕ್ಲಬ್ಗಳು",
    forums: "ಚರ್ಚೆ ವೇದಿಕೆಗಳು",
    questionPaper: "ಪ್ರಶ್ನೆ ಪತ್ರಿಕೆ",
    analytics: "ವಿಶ್ಲೇಷಣೆ",
    auditLog: "ಆಡಿಟ್ ಲಾಗ್",
    add: "ಸೇರಿಸು",
    edit: "ಸಂಪಾದಿಸು",
    delete: "ಅಳಿಸು",
    save: "ಉಳಿಸು",
    cancel: "ರದ್ದು",
    search: "ಹುಡುಕು",
    close: "ಮುಚ್ಚು",
    submit: "ಸಲ್ಲಿಸು",
    download: "ಡೌನ್‌ಲೋಡ್",
    upload: "ಅಪ್‌ಲೋಡ್",
    all: "ಎಲ್ಲ",
    collegeStudents: "ಕಾಲೇಜು ವಿದ್ಯಾರ್ಥಿಗಳು",
    collegeFaculty: "ಕಾಲೇಜು ಅಧ್ಯಾಪಕರು",
    parentPortal: "ಪಾಲಕರ ಪೋರ್ಟಲ್",
    school: "ಶಾಲೆ",
    college: "ಕಾಲೇಜು",
    general: "ಸಾಮಾನ್ಯ",
    studentsPage: "ವಿದ್ಯಾರ್ಥಿ ನಿರ್ವಹಣೆ",
    teachersPage: "ಶಿಕ್ಷಕ ನಿರ್ವಹಣೆ",
    classesPage: "ತರಗತಿ ನಿರ್ವಹಣೆ",
    attendancePage: "ಹಾಜರಾತಿ ಟ್ರ್ಯಾಕರ್",
    gradesPage: "ಶ್ರೇಣಿ ನಿರ್ವಹಣೆ",
    timetablePage: "ಸಮಯ ಪಟ್ಟಿ",
    examsPage: "ಪರೀಕ್ಷೆಗಳು",
    announcementsPage: "ಪ್ರಕಟಣೆಗಳು",
    libraryPage: "ಗ್ರಂಥಾಲಯ",
    financePage: "ಹಣಕಾಸು",
    eventsPage: "ಕಾರ್ಯಕ್ರಮಗಳು",
    subjectsPage: "ವಿಷಯಗಳು",
    reportsPage: "ವರದಿಗಳು",
    messagesPage: "ಸಂದೇಶಗಳು",
    settingsPage: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    documentsPage: "ದಾಖಲೆಗಳು",
    transportPage: "ಸಾರಿಗೆ ನಿರ್ವಹಣೆ",
    homeworkPage: "ಗೃಹಕಾರ್ಯ",
    analyticsPage: "ವಿಶ್ಲೇಷಣೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    auditLogPage: "ಆಡಿಟ್ ಲಾಗ್",
    clubsPage: "ಕ್ಲಬ್ಗಳು",
    forumsPage: "ಚರ್ಚೆ ವೇದಿಕೆಗಳು",
    addStudent: "ವಿದ್ಯಾರ್ಥಿ ಸೇರಿಸು",
    addTeacher: "ಶಿಕ್ಷಕ ಸೇರಿಸು",
    addClass: "ತರಗತಿ ಸೇರಿಸು",
    addEvent: "ಕಾರ್ಯಕ್ರಮ ಸೇರಿಸು",
    addSubject: "ವಿಷಯ ಸೇರಿಸು",
    markAttendance: "ಹಾಜರಾತಿ ಗುರುತಿಸು",
    addGrade: "ಶ್ರೇಣಿ ಸೇರಿಸು",
    addExam: "ಪರೀಕ್ಷೆ ಸೇರಿಸು",
    addAnnouncement: "ಪ್ರಕಟಣೆ ಸೇರಿಸು",
    compose: "ಬರೆಯಿರಿ",
    inbox: "ಇನ್‌ಬಾಕ್ಸ್",
    sent: "ಕಳುಹಿಸಿದ",
    starred: "ನಕ್ಷತ್ರ",
    trash: "ಕಸ",
    present: "ಹಾಜರು",
    absent: "ಗೈರು",
    pending: "ಬಾಕಿ",
    paid: "ಪಾವತಿ",
    unpaid: "ಪಾವತಿ ಬಾಕಿ",
    payOnline: "ಆನ್‌ಲೈನ್ ಪಾವತಿ",
    viewDetails: "ವಿವರಗಳು",
    printReport: "ವರದಿ ಮುದ್ರಿಸು",
    exportCSV: "CSV ರಫ್ತು",
    name: "ಹೆಸರು",
    class: "ತರಗತಿ",
    section: "ವಿಭಾಗ",
    subject: "ವಿಷಯ",
    date: "ದಿನಾಂಕ",
    status: "ಸ್ಥಿತಿ",
    actions: "ಕ್ರಿಯೆಗಳು",
    total: "ಒಟ್ಟು",
    fee: "ಶುಲ್ಕ",
    amount: "ಮೊತ್ತ",
    type: "ಪ್ರಕಾರ",
    description: "ವಿವರಣೆ",
    phone: "ಫೋನ್",
    email: "ಇಮೇಲ್",
    address: "ವಿಳಾಸ",
    gender: "ಲಿಂಗ",
    male: "ಪುರುಷ",
    female: "ಮಹಿಳೆ",
    role: "ಪಾತ್ರ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    confirm: "ದೃಢಪಡಿಸು",
    update: "ನವೀಕರಿಸು",
    profile: "ಪ್ರೊಫೈಲ್",
    logout: "ಲಾಗ್ ಔಟ್",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    welcome: "ಸ್ವಾಗತ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    noData: "ಡೇಟಾ ಇಲ್ಲ",
    filter: "ಫಿಲ್ಟರ್",
    reset: "ಮರುಹೊಂದಿಸು",
    print: "ಮುದ್ರಿಸು",
    share: "ಹಂಚಿಕೊಳ್ಳಿ",
    approve: "ಅನುಮೋದಿಸು",
    reject: "ತಿರಸ್ಕರಿಸು",
    reserve: "ಮೀಸಲಿಡು",
    return: "ಹಿಂದಿರುಗಿಸು",
    fine: "ದಂಡ",
    available: "ಲಭ್ಯ",
    checkedOut: "ಹೊರಗೆ ತೆಗೆದ",
    reserved: "ಮೀಸಲಾದ",
    overdue: "ಗಡುವು ಮೀರಿದ",
    totalClasses: "ಒಟ್ಟು ತರಗತಿಗಳು",
    totalStudents: "ಒಟ್ಟು ವಿದ್ಯಾರ್ಥಿಗಳು",
    avgClassSize: "ಸರಾಸರಿ ತರಗತಿ ಗಾತ್ರ",
    classTeacher: "ತರಗತಿ ಶಿಕ್ಷಕ",
    room: "ಕೊಠಡಿ",
    editClass: "ತರಗತಿ ಸಂಪಾದಿಸು",
    addNewClass: "ಹೊಸ ತರಗತಿ ಸೇರಿಸು",
    searchClasses: "ತರಗತಿಗಳನ್ನು ಹುಡುಕಿ...",
    noClassesFound: "ತರಗತಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    deleteClass: "ತರಗತಿ ಅಳಿಸು",
    activeClasses: "ತರಗತಿಗಳು ಸಕ್ರಿಯ",
    gradeName: "ಶ್ರೇಣಿ/ತರಗತಿ ಹೆಸರು",
    numberOfStudents: "ವಿದ್ಯಾರ್ಥಿಗಳ ಸಂಖ್ಯೆ",
    roomNumber: "ಕೊಠಡಿ ಸಂಖ್ಯೆ",
    selectTeacher: "ಶಿಕ್ಷಕರನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    studentEnrollmentTrend: "ವಿದ್ಯಾರ್ಥಿ ನೋಂದಣಿ ಪ್ರವೃತ್ತಿ",
    monthlyPerformanceScore: "ಮಾಸಿಕ ಕಾರ್ಯಕ್ಷಮತೆ ಸ್ಕೋರ್",
    topStudents: "ಅಗ್ರ ವಿದ್ಯಾರ್ಥಿಗಳು",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    attendanceOverview: "ಹಾಜರಾತಿ ಅವಲೋಕನ",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ! ಇಲ್ಲಿ ನಿಮ್ಮ ಶಾಲೆಯ ಅವಲೋಕನ ಇದೆ.",
    rank: "ರ್ಯಾಂಕ್",
    average: "ಸರಾಸರಿ",
    viewAll: "ಎಲ್ಲ ನೋಡಿ",
    scheduleExam: "ಪರೀಕ್ಷೆ ನಿಗದಿ",
    postAnnouncement: "ಪ್ರಕಟಣೆ ಪೋಸ್ಟ್",
    feeCollection: "ಶುಲ್ಕ ಸಂಗ್ರಹ",
    viewReports: "ವರದಿ ನೋಡಿ",
    myTimetable: "ನನ್ನ ಸಮಯ ಪಟ್ಟಿ",
    leaveApplication: "ರಜೆ ಅರ್ಜಿ",
    attendanceSummary: "ಹಾಜರಾತಿ ಸಾರಾಂಶ",
    reportCard: "ರಿಪೋರ್ಟ್ ಕಾರ್ಡ್",
    feeHistory: "ಶುಲ್ಕ ಇತಿಹಾಸ",
    gpaCalculator: "GPA ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    digitalLibrary: "ಡಿಜಿಟಲ್ ಗ್ರಂಥಾಲಯ",
    bookReservation: "ಪುಸ್ತಕ ಮೀಸಲಾತಿ",
    budgetReport: "ಬಜೆಟ್ ವರದಿ",
    paymentHistory: "ಪಾವತಿ ಇತಿಹಾಸ",
    noResults: "ಫಲಿತಾಂಶಗಳಿಲ್ಲ",
    language: "ಭಾಷೆ",
    backgroundColor: "ಹಿನ್ನೆಲೆ ಬಣ್ಣ",
    saveChanges: "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
    profileSettings: "ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    security: "ಭದ್ರತೆ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    schoolSettings: "ಶಾಲೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    monday: "ಸೋಮವಾರ",
    tuesday: "ಮಂಗಳವಾರ",
    wednesday: "ಬುಧವಾರ",
    thursday: "ಗುರುವಾರ",
    friday: "ಶುಕ್ರವಾರ",
    saturday: "ಶನಿವಾರ",
    sunday: "ಭಾನುವಾರ",
    selectClass: "ತರಗತಿ ಆರಿಸಿ",
    selectDay: "ದಿನ ಆರಿಸಿ",
    selectExam: "ಪರೀಕ್ಷೆ ಆರಿಸಿ",
    selectSubject: "ವಿಷಯ ಆರಿಸಿ",
    period: "ಅವಧಿ",
    saveAttendance: "ಹಾಜರಾತಿ ಉಳಿಸಿ",
    saveGrades: "ಗ್ರೇಡ್‌ಗಳು ಉಳಿಸಿ",
    attendanceRate: "ಹಾಜರಾತಿ ದರ",
    studentName: "ವಿದ್ಯಾರ್ಥಿ ಹೆಸರು",
    rollNo: "ರೋಲ್ ನಂ.",
    age: "ವಯಸ್ಸು",
    department: "ವಿಭಾಗ",
    qualification: "ಅರ್ಹತೆ",
    contactNo: "ಸಂಪರ್ಕ",
    totalTeachers: "ಒಟ್ಟು ಶಿಕ್ಷಕರು",
    active: "ಸಕ್ರಿಯ",
    departments: "ವಿಭಾಗಗಳು",
    linkedAccounts: "ಲಿಂಕ್ ಮಾಡಿದ ಖಾತೆಗಳು",
    notLinked: "ಲಿಂಕ್ ಆಗಿಲ್ಲ",
    examName: "ಪರೀಕ್ಷೆ ಹೆಸರು",
    maxMarks: "ಗರಿಷ್ಠ ಅಂಕಗಳು",
    enterMarks: "ಅಂಕಗಳು ನಮೂದಿಸಿ",
    audience: "ಪ್ರೇಕ್ಷಕರು",
    priorityLabel: "ಆದ್ಯತೆ",
    high: "ಹೆಚ್ಚು",
    medium: "ಮಧ್ಯಮ",
    low: "ಕಡಿಮೆ",
    addEventBtn: "ಕಾರ್ಯಕ್ರಮ ಸೇರಿಸಿ",
    location: "ಸ್ಥಳ",
    participants: "ಭಾಗವಹಿಸುವವರು",
    eventTitle: "ಕಾರ್ಯಕ್ರಮ ಶೀರ್ಷಿಕೆ",
    addEntry: "ಪ್ರವೇಶ ಸೇರಿಸಿ",
    noEntriesFound: "ಪ್ರವೇಶಗಳಿಲ್ಲ",
    weeklySchedule: "ವಾರದ ವೇಳಾಪಟ್ಟಿ",
    removeEntry: "ಪ್ರವೇಶ ತೆಗೆಯಿರಿ",
    searchStudents: "ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಹುಡುಕಿ...",
    searchTeachers: "ಶಿಕ್ಷಕರನ್ನು ಹುಡುಕಿ...",
    searchExams: "ಪರೀಕ್ಷೆ ಹುಡುಕಿ...",
    searchEvents: "ಕಾರ್ಯಕ್ರಮ ಹುಡುಕಿ...",
    searchBooks: "ಪುಸ್ತಕ ಹುಡುಕಿ...",
    returnBook: "ಹಿಂತಿರುಗಿಸಿ",
    issuedBooks: "ನೀಡಿದ ಪುಸ್ತಕಗಳು",
    finesTab: "ದಂಡ",
    reservationsTab: "ಮೀಸಲಾತಿ",
    physicalBooks: "ಭೌತಿಕ ಪುಸ್ತಕಗಳು",
    digitalBooksTab: "ಡಿಜಿಟಲ್ ಗ್ರಂಥಾಲಯ",
    uploadBook: "ಪುಸ್ತಕ ಅಪ್‌ಲೋಡ್",
    budgetOverview: "ಬಜೆಟ್ ಅವಲೋಕನ",
    income: "ಆದಾಯ",
    expenses: "ವೆಚ್ಚಗಳು",
    balance: "ಉಳಿಕೆ",
    feeReminder: "ಶುಲ್ಕ ಜ್ಞಾಪನೆ",
    paymentMethod: "ಪಾವತಿ ವಿಧಾನ",
    transactionHistory: "ವ್ಯವಹಾರ ಇತಿಹಾಸ",
    uploadFile: "ಫೈಲ್ ಅಪ್‌ಲೋಡ್",
    noDocuments: "ದಾಖಲೆಗಳಿಲ್ಲ",
    routeName: "ಮಾರ್ಗ ಹೆಸರು",
    driverName: "ಚಾಲಕ",
    vehicle: "ವಾಹನ",
    stops: "ನಿಲ್ದಾಣಗಳು",
    importData: "ಡೇಟಾ ಆಮದು",
    exportData: "ಡೇಟಾ ರಫ್ತು",
    startDate: "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
    endDate: "ಕೊನೆ ದಿನಾಂಕ",
    currentYear: "ಪ್ರಸ್ತುತ ವರ್ಷ",
    forumTitle: "ಫೋರಂ ಶೀರ್ಷಿಕೆ",
    newPost: "ಹೊಸ ಪೋಸ್ಟ್",
    lastActivity: "ಕೊನೆ ಚಟುವಟಿಕೆ",
    clubName: "ಕ್ಲಬ್ ಹೆಸರು",
    joinClub: "ಕ್ಲಬ್ ಸೇರಿ",
    requirements: "ಅವಶ್ಯಕತೆಗಳು",
    questionTypeLabel: "ಪ್ರಶ್ನೆ ವಿಧ",
    mcq: "MCQ",
    shortAnswer: "ಸಂಕ್ಷಿಪ್ತ ಉತ್ತರ",
    essayType: "ಪ್ರಬಂಧ",
    addQuestion: "ಪ್ರಶ್ನೆ ಸೇರಿಸಿ",
    assignedTo: "ನಿಯೋಜಿಸಲಾಗಿದೆ",
    submittedBy: "ಸಲ್ಲಿಸಿದವರು",
    gradeSubmission: "ಗ್ರೇಡ್",
    lessonTitle: "ಪಾಠ ಶೀರ್ಷಿಕೆ",
    objective: "ಉದ್ದೇಶ",
    exportCSVBtn: "CSV ರಫ್ತು",
    scheduleNewExam: "ಹೊಸ ಪರೀಕ್ಷೆ",
    enterGrades: "ಗ್ರೇಡ್‌ಗಳು ನಮೂದಿಸಿ",
    selectClassFirst: "ಹಾಜರಾತಿಗೆ ತರಗತಿ ಆರಿಸಿ",
    attendanceMark: "ಗುರುತು",
    totalFees: "ಒಟ್ಟು ಶುಲ್ಕ",
    collected: "ಸಂಗ್ರಹಿಸಲಾಗಿದೆ",
    pendingFees: "ಬಾಕಿ",
    payNow: "ಈಗ ಪಾವತಿಸಿ",
    configureStripe: "Stripe ಕಾನ್ಫಿಗರ್",
    uploadDate: "ಅಪ್‌ಲೋಡ್ ದಿನಾಂಕ",
    fileSize: "ಫೈಲ್ ಗಾತ್ರ",
    category: "ವಿಭಾಗ",
  },
  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    students: "വിദ്യാർഥികൾ",
    teachers: "അധ്യാപകർ",
    classes: "ക്ലാസുകൾ",
    attendance: "ഹാജർ",
    grades: "ഗ്രേഡുകൾ",
    timetable: "സമയക്രമം",
    exams: "പരീക്ഷകൾ",
    announcements: "അറിയിപ്പുകൾ",
    library: "ഗ്രന്ഥശാല",
    finance: "ധനകാര്യം",
    events: "പരിപാടികൾ",
    subjects: "വിഷയങ്ങൾ",
    reports: "റിപ്പോർട്ടുകൾ",
    messages: "സന്ദേശങ്ങൾ",
    settings: "ക്രമീകരണങ്ങൾ",
    documents: "രേഖകൾ",
    transport: "ഗതാഗതം",
    homework: "ഗൃഹപാഠം",
    bulkImport: "ബൾക്ക് ഇറക്കുമതി",
    academicYear: "അധ്യായന വർഷം",
    clubs: "ക്ലബ്ബുകൾ",
    forums: "ചർച്ചാ വേദികൾ",
    questionPaper: "ചോദ്യപേപ്പർ",
    analytics: "വിശകലനം",
    auditLog: "ഓഡിറ്റ് ലോഗ്",
    add: "ചേർക്കുക",
    edit: "തിരുത്തുക",
    delete: "നീക്കുക",
    save: "സേവ്",
    cancel: "റദ്ദ്",
    search: "തിരയുക",
    close: "അടക്കുക",
    submit: "സമർപ്പിക്കുക",
    download: "ഡൗൺലോഡ്",
    upload: "അപ്‌ലോഡ്",
    all: "എല്ലാം",
    collegeStudents: "കോളേജ് വിദ്യാർഥികൾ",
    collegeFaculty: "കോളേജ് അധ്യാപകർ",
    parentPortal: "രക്ഷിതാക്കളുടെ പോർട്ടൽ",
    school: "സ്കൂൾ",
    college: "കോളേജ്",
    general: "പൊതു",
    studentsPage: "വിദ്യാർഥി മാനേജ്‌മെന്റ്",
    teachersPage: "അധ്യാപക മാനേജ്‌മെന്റ്",
    classesPage: "ക്ലാസ് മാനേജ്‌മെന്റ്",
    attendancePage: "ഹാജർ ട്രാക്കർ",
    gradesPage: "ഗ്രേഡ് മാനേജ്‌മെന്റ്",
    timetablePage: "സമയക്രമം",
    examsPage: "പരീക്ഷകൾ",
    announcementsPage: "അറിയിപ്പുകൾ",
    libraryPage: "ഗ്രന്ഥശാല",
    financePage: "ധനകാര്യം",
    eventsPage: "പരിപാടികൾ",
    subjectsPage: "വിഷയങ്ങൾ",
    reportsPage: "റിപ്പോർട്ടുകൾ",
    messagesPage: "സന്ദേശങ്ങൾ",
    settingsPage: "ക്രമീകരണങ്ങൾ",
    documentsPage: "രേഖകൾ",
    transportPage: "ഗതാഗത മാനേജ്‌മെന്റ്",
    homeworkPage: "ഗൃഹപാഠം",
    analyticsPage: "വിശകലന ഡാഷ്‌ബോർഡ്",
    auditLogPage: "ഓഡിറ്റ് ലോഗ്",
    clubsPage: "ക്ലബ്ബുകൾ",
    forumsPage: "ചർച്ചാ വേദികൾ",
    addStudent: "വിദ്യാർഥിയെ ചേർക്കുക",
    addTeacher: "അധ്യാപകനെ ചേർക്കുക",
    addClass: "ക്ലാസ് ചേർക്കുക",
    addEvent: "പരിപാടി ചേർക്കുക",
    addSubject: "വിഷയം ചേർക്കുക",
    markAttendance: "ഹാജർ അടയാളപ്പെടുത്തുക",
    addGrade: "ഗ്രേഡ് ചേർക്കുക",
    addExam: "പരീക്ഷ ചേർക്കുക",
    addAnnouncement: "അറിയിപ്പ് ചേർക്കുക",
    compose: "എഴുതുക",
    inbox: "ഇൻബോക്സ്",
    sent: "അയച്ചത്",
    starred: "നക്ഷത്രം",
    trash: "ട്രാഷ്",
    present: "ഹാജർ",
    absent: "അഹാജർ",
    pending: "തീർപ്പുകൽ",
    paid: "അടച്ചു",
    unpaid: "അടച്ചിട്ടില്ല",
    payOnline: "ഓൺലൈൻ പേ",
    viewDetails: "വിശദാംശങ്ങൾ",
    printReport: "റിപ്പോർട്ട് പ്രിന്റ്",
    exportCSV: "CSV കയറ്റുമതി",
    name: "പേര്",
    class: "ക്ലാസ്",
    section: "വിഭാഗം",
    subject: "വിഷയം",
    date: "തീയതി",
    status: "നില",
    actions: "പ്രവർത്തനങ്ങൾ",
    total: "ആകെ",
    fee: "ഫീസ്",
    amount: "തുക",
    type: "തരം",
    description: "വിവരണം",
    phone: "ഫോൺ",
    email: "ഇമെയിൽ",
    address: "മേൽവിലാസം",
    gender: "ലിംഗം",
    male: "പുരുഷൻ",
    female: "സ്ത്രീ",
    role: "റോൾ",
    password: "പാസ്‌വേഡ്",
    confirm: "സ്ഥിരീകരിക്കുക",
    update: "അപ്‌ഡേറ്റ്",
    profile: "പ്രൊഫൈൽ",
    logout: "ലോഗ് ഔട്ട്",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്",
    welcome: "സ്വാഗതം",
    loading: "ലോഡ് ആകുന്നു...",
    noData: "ഡേറ്റ ഇല്ല",
    filter: "ഫിൽറ്റർ",
    reset: "റീസെറ്റ്",
    print: "പ്രിന്റ്",
    share: "പങ്കിടുക",
    approve: "അംഗീകരിക്കുക",
    reject: "നിരസിക്കുക",
    reserve: "റിസർവ്",
    return: "തിരിച്ചുനൽകുക",
    fine: "പിഴ",
    available: "ലഭ്യം",
    checkedOut: "കൊണ്ടുപോയി",
    reserved: "റിസർവ് ആയി",
    overdue: "കാലഹരണം",
    totalClasses: "ആകെ ക്ലാസുകൾ",
    totalStudents: "ആകെ വിദ്യാർഥികൾ",
    avgClassSize: "ശരാശരി ക്ലാസ് വലിപ്പം",
    classTeacher: "ക്ലാസ് അധ്യാപകർ",
    room: "മുറി",
    editClass: "ക്ലാസ് തിരുത്തുക",
    addNewClass: "പുതിയ ക്ലാസ് ചേർക്കുക",
    searchClasses: "ക്ലാസ് തിരയുക...",
    noClassesFound: "ക്ലാസ് കണ്ടെത്തിയില്ല",
    deleteClass: "ക്ലാസ് ഇല്ലാതാക്കുക",
    activeClasses: "ക്ലാസ് സജീവം",
    gradeName: "ഗ്രേഡ്/ക്ലാസ് പേര്",
    numberOfStudents: "വിദ്യാർഥി എണ്ണം",
    roomNumber: "മുറി നമ്പർ",
    selectTeacher: "അധ്യാപകനെ തിരഞ്ഞെടുക്കുക",
    quickActions: "ദ്രുത പ്രവർത്തനങ്ങൾ",
    studentEnrollmentTrend: "വിദ്യാർഥി ചേർക്കൽ ട്രെൻഡ്",
    monthlyPerformanceScore: "മാസ പ്രകടന സ്കോർ",
    topStudents: "മികച്ച വിദ്യാർഥികൾ",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    attendanceOverview: "ഹാജർ അവലോകനം",
    welcomeBack: "തിരിച്ചു സ്വാഗതം! ഇവിടെ നിങ്ങളുടെ സ്കൂൾ അവലോകനം.",
    rank: "റാങ്ക്",
    average: "ശരാശരി",
    viewAll: "എല്ലാം കാണുക",
    scheduleExam: "പരീക്ഷ ഷെഡ്യൂൾ",
    postAnnouncement: "അറിയിപ്പ് പോസ്റ്റ്",
    feeCollection: "ഫീസ് ശേഖരണം",
    viewReports: "റിപ്പോർട്ട് കാണുക",
    myTimetable: "എന്റെ സമയക്രമം",
    leaveApplication: "അവധി അപേക്ഷ",
    attendanceSummary: "ഹാജർ സംഗ്രഹം",
    reportCard: "റിപ്പോർട്ട് കാർഡ്",
    feeHistory: "ഫീസ് ചരിത്രം",
    gpaCalculator: "GPA കാൽക്കുലേറ്റർ",
    digitalLibrary: "ഡിജിറ്റൽ ഗ്രന്ഥശാല",
    bookReservation: "പുസ്തക റിസർവേഷൻ",
    budgetReport: "ബഡ്ജറ്റ് റിപ്പോർട്ട്",
    paymentHistory: "പേമെന്റ് ചരിത്രം",
    noResults: "ഫലങ്ങൾ ഇല്ല",
    language: "ഭാഷ",
    backgroundColor: "പശ്ചാത്തല നിറം",
    saveChanges: "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
    profileSettings: "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ",
    security: "സുരക്ഷ",
    notifications: "അറിയിപ്പുകൾ",
    schoolSettings: "സ്കൂൾ ക്രമീകരണങ്ങൾ",
    monday: "തിങ്കൾ",
    tuesday: "ചൊവ്വ",
    wednesday: "ബുധൻ",
    thursday: "വ്യാഴം",
    friday: "വെള്ളി",
    saturday: "ശനി",
    sunday: "ഞായർ",
    selectClass: "ക്ലാസ് തിരഞ്ഞെടുക്കുക",
    selectDay: "ദിവസം തിരഞ്ഞെടുക്കുക",
    selectExam: "പരീക്ഷ തിരഞ്ഞെടുക്കുക",
    selectSubject: "വിഷയം തിരഞ്ഞെടുക്കുക",
    period: "പിരീഡ്",
    saveAttendance: "ഹാജർ സേവ് ചെയ്യുക",
    saveGrades: "ഗ്രേഡുകൾ സേവ് ചെയ്യുക",
    attendanceRate: "ഹാജർ നിരക്ക്",
    studentName: "വിദ്യാർഥി പേര്",
    rollNo: "റോൾ നം.",
    age: "പ്രായം",
    department: "വകുപ്പ്",
    qualification: "യോഗ്യത",
    contactNo: "ബന്ധപ്പെടുക",
    totalTeachers: "മൊത്തം അദ്ധ്യാപകർ",
    active: "സജീവം",
    departments: "വകുപ്പുകൾ",
    linkedAccounts: "ലിങ്ക്ഡ് അക്കൗണ്ടുകൾ",
    notLinked: "ലിങ്ക് ചെയ്തിട്ടില്ല",
    examName: "പരീക്ഷ പേര്",
    maxMarks: "പരമാവധി മാർക്ക്",
    enterMarks: "മാർക്ക് നൽകുക",
    audience: "പ്രേക്ഷകർ",
    priorityLabel: "മുൻഗണന",
    high: "ഉയർന്ന",
    medium: "മധ്യം",
    low: "താഴ്ന്ന",
    addEventBtn: "ഇവൻ്റ് ചേർക്കുക",
    location: "സ്ഥലം",
    participants: "പങ്കെടുക്കുന്നവർ",
    eventTitle: "ഇവൻ്റ് ശീർഷകം",
    addEntry: "എൻട്രി ചേർക്കുക",
    noEntriesFound: "എൻട്രികൾ ഇല്ല",
    weeklySchedule: "വാരികമായ ഷെഡ്യൂൾ",
    removeEntry: "എൻട്രി നീക്കം ചെയ്യുക",
    searchStudents: "വിദ്യാർഥികളെ തിരയുക...",
    searchTeachers: "അദ്ധ്യാപകരെ തിരയുക...",
    searchExams: "പരീക്ഷ തിരയുക...",
    searchEvents: "ഇവൻ്റ് തിരയുക...",
    searchBooks: "പുസ്തകം തിരയുക...",
    returnBook: "തിരിച്ചുനൽകുക",
    issuedBooks: "നൽകിയ പുസ്തകങ്ങൾ",
    finesTab: "പിഴ",
    reservationsTab: "റിസർവേഷൻ",
    physicalBooks: "ഭൗതിക പുസ്തകങ്ങൾ",
    digitalBooksTab: "ഡിജിറ്റൽ ലൈബ്രറി",
    uploadBook: "പുസ്തകം അപ്‌ലോഡ്",
    budgetOverview: "ബജറ്റ് അവലോകനം",
    income: "വരുമാനം",
    expenses: "ചെലവുകൾ",
    balance: "ബാക്കി",
    feeReminder: "ഫീ ഓർമ്മപ്പെടുത്തൽ",
    paymentMethod: "പണമടക്കൽ രീതി",
    transactionHistory: "ഇടപാട് ചരിത്രം",
    uploadFile: "ഫയൽ അപ്‌ലോഡ്",
    noDocuments: "രേഖകൾ ഇല്ല",
    routeName: "റൂട്ട് പേര്",
    driverName: "ഡ്രൈവർ",
    vehicle: "വാഹനം",
    stops: "സ്റ്റോപ്പുകൾ",
    importData: "ഡേറ്റ ഇറക്കുമതി",
    exportData: "ഡേറ്റ കയറ്റുമതി",
    startDate: "ആരംഭ തീയതി",
    endDate: "അവസാന തീയതി",
    currentYear: "നടപ്പ് വർഷം",
    forumTitle: "ഫോറം ശീർഷകം",
    newPost: "പുതിയ പോസ്റ്റ്",
    lastActivity: "അവസാന പ്രവർത്തനം",
    clubName: "ക്ലബ് പേര്",
    joinClub: "ക്ലബ് ചേരുക",
    requirements: "ആവശ്യകതകൾ",
    questionTypeLabel: "ചോദ്യ തരം",
    mcq: "MCQ",
    shortAnswer: "ഹ്രസ്വ ഉത്തരം",
    essayType: "ഉപന്യാസം",
    addQuestion: "ചോദ്യം ചേർക്കുക",
    assignedTo: "നിയോഗിച്ചിരിക്കുന്നു",
    submittedBy: "സമർപ്പിച്ചവർ",
    gradeSubmission: "ഗ്രേഡ്",
    lessonTitle: "പാഠ ശീർഷകം",
    objective: "ലക്ഷ്യം",
    exportCSVBtn: "CSV കയറ്റുമതി",
    scheduleNewExam: "പുതിയ പരീക്ഷ",
    enterGrades: "ഗ്രേഡുകൾ നൽകുക",
    selectClassFirst: "ഹാജർ ക്ലാസ് തിരഞ്ഞെടുക്കുക",
    attendanceMark: "അടയാളപ്പെടുത്തുക",
    totalFees: "മൊത്തം ഫീ",
    collected: "ശേഖരിച്ചു",
    pendingFees: "ബാക്കി",
    payNow: "ഇപ്പോൾ അടക്കുക",
    configureStripe: "Stripe ക്രമീകരിക്കുക",
    uploadDate: "അപ്‌ലോഡ് തീയതി",
    fileSize: "ഫയൽ വലിപ്പം",
    category: "വിഭാഗം",
  },
  bn: {
    dashboard: "ড্যাশবোর্ড",
    students: "ছাত্রছাত্রী",
    teachers: "শিক্ষক",
    classes: "শ্রেণী",
    attendance: "উপস্থিতি",
    grades: "গ্রেড",
    timetable: "সময়সূচি",
    exams: "পরীক্ষা",
    announcements: "ঘোষণা",
    library: "পাঠাগার",
    finance: "অর্থ",
    events: "অনুষ্ঠান",
    subjects: "বিষয়",
    reports: "প্রতিবেদন",
    messages: "বার্তা",
    settings: "সেটিংস",
    documents: "নথি",
    transport: "পরিবহন",
    homework: "গৃহকার্য",
    bulkImport: "বাল্ক আমদানি",
    academicYear: "শিক্ষাবর্ষ",
    clubs: "ক্লাব",
    forums: "আলোচনা মঞ্চ",
    questionPaper: "প্রশ্নপত্র",
    analytics: "বিশ্লেষণ",
    auditLog: "অডিট লগ",
    add: "যোগ করুন",
    edit: "সম্পাদনা",
    delete: "মুছুন",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    search: "খোঁজুন",
    close: "বন্ধ করুন",
    submit: "জমা দিন",
    download: "ডাউনলোড",
    upload: "আপলোড",
    all: "সব",
    collegeStudents: "কলেজ ছাত্রছাত্রী",
    collegeFaculty: "কলেজ শিক্ষক",
    parentPortal: "অভিভাবক পোর্টাল",
    school: "বিদ্যালয়",
    college: "কলেজ",
    general: "সাধারণ",
    studentsPage: "ছাত্র ব্যবস্থাপনা",
    teachersPage: "শিক্ষক ব্যবস্থাপনা",
    classesPage: "শ্রেণী ব্যবস্থাপনা",
    attendancePage: "উপস্থিতি ট্র্যাকার",
    gradesPage: "গ্রেড ব্যবস্থাপনা",
    timetablePage: "সময়সূচি",
    examsPage: "পরীক্ষা",
    announcementsPage: "ঘোষণা",
    libraryPage: "পাঠাগার",
    financePage: "অর্থ",
    eventsPage: "অনুষ্ঠান",
    subjectsPage: "বিষয়",
    reportsPage: "প্রতিবেদন",
    messagesPage: "বার্তা",
    settingsPage: "সেটিংস",
    documentsPage: "নথি",
    transportPage: "পরিবহন ব্যবস্থাপনা",
    homeworkPage: "গৃহকার্য",
    analyticsPage: "বিশ্লেষণ ড্যাশবোর্ড",
    auditLogPage: "অডিট লগ",
    clubsPage: "ক্লাব",
    forumsPage: "আলোচনা মঞ্চ",
    addStudent: "ছাত্র যোগ করুন",
    addTeacher: "শিক্ষক যোগ করুন",
    addClass: "শ্রেণী যোগ করুন",
    addEvent: "অনুষ্ঠান যোগ করুন",
    addSubject: "বিষয় যোগ করুন",
    markAttendance: "উপস্থিতি চিহ্নিত করুন",
    addGrade: "গ্রেড যোগ করুন",
    addExam: "পরীক্ষা যোগ করুন",
    addAnnouncement: "ঘোষণা যোগ করুন",
    compose: "লিখুন",
    inbox: "ইনবক্স",
    sent: "প্রেরিত",
    starred: "তারকাচিহ্নিত",
    trash: "ট্র্যাশ",
    present: "উপস্থিত",
    absent: "অনুপস্থিত",
    pending: "মুলতুবি",
    paid: "পরিশোধিত",
    unpaid: "অপরিশোধিত",
    payOnline: "অনলাইন পেমেন্ট",
    viewDetails: "বিস্তারিত",
    printReport: "রিপোর্ট প্রিন্ট",
    exportCSV: "CSV রফতানি",
    name: "নাম",
    class: "শ্রেণী",
    section: "বিভাগ",
    subject: "বিষয়",
    date: "তারিখ",
    status: "অবস্থা",
    actions: "ক্রিয়া",
    total: "মোট",
    fee: "ফি",
    amount: "পরিমাণ",
    type: "ধরন",
    description: "বিবরণ",
    phone: "ফোন",
    email: "ইমেইল",
    address: "ঠিকানা",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    role: "ভূমিকা",
    password: "পাসওয়ার্ড",
    confirm: "নিশ্চিত করুন",
    update: "আপডেট",
    profile: "প্রোফাইল",
    logout: "লগ আউট",
    login: "লগইন",
    signup: "সাইন আপ",
    welcome: "স্বাগতম",
    loading: "লোড হচ্ছে...",
    noData: "কোনো তথ্য নেই",
    filter: "ফিল্টার",
    reset: "রিসেট",
    print: "মুদ্রণ",
    share: "শেয়ার",
    approve: "অনুমোদন",
    reject: "প্রত্যাখ্যান",
    reserve: "সংরক্ষণ",
    return: "ফেরত",
    fine: "জরিমানা",
    available: "পাওয়া যাচ্ছে",
    checkedOut: "নেওয়া হয়েছে",
    reserved: "সংরক্ষিত",
    overdue: "মেয়াদোত্তীর্ণ",
    totalClasses: "মোট শ্রেণী",
    totalStudents: "মোট ছাত্রছাত্রী",
    avgClassSize: "গড় ক্লাস আকার",
    classTeacher: "শ্রেণী শিক্ষক",
    room: "ঘর",
    editClass: "শ্রেণী সম্পাদনা",
    addNewClass: "নতুন শ্রেণী যোগ করুন",
    searchClasses: "শ্রেণী খুঁজুন...",
    noClassesFound: "কোনো শ্রেণী পাওয়া যায়নি",
    deleteClass: "শ্রেণী মুছুন",
    activeClasses: "শ্রেণী সক্রিয়",
    gradeName: "গ্রেড/শ্রেণীর নাম",
    numberOfStudents: "ছাত্রসংখ্যা",
    roomNumber: "ঘর নম্বর",
    selectTeacher: "শিক্ষক নির্বাচন করুন",
    quickActions: "দ্রুত কার্যক্রম",
    studentEnrollmentTrend: "শিক্ষার্থী ভর্তি প্রবণতা",
    monthlyPerformanceScore: "মাসিক পারফরম্যান্স স্কোর",
    topStudents: "শীর্ষ শিক্ষার্থী",
    recentActivity: "সাম্প্রতিক কার্যক্রম",
    attendanceOverview: "উপস্থিতি পর্যালোচনা",
    welcomeBack: "ফিরে আসার স্বাগতম! এখানে আপনার স্কুলের সারাংশ।",
    rank: "র‍্যাংক",
    average: "গড়",
    viewAll: "সব দেখুন",
    scheduleExam: "পরীক্ষার সময়সূচি",
    postAnnouncement: "ঘোষণা পোস্ট",
    feeCollection: "ফি সংগ্রহ",
    viewReports: "রিপোর্ট দেখুন",
    myTimetable: "আমার সময়সূচি",
    leaveApplication: "ছুটির আবেদন",
    attendanceSummary: "উপস্থিতি সারসংক্ষেপ",
    reportCard: "রিপোর্ট কার্ড",
    feeHistory: "ফি ইতিহাস",
    gpaCalculator: "GPA ক্যালকুলেটর",
    digitalLibrary: "ডিজিটাল পাঠাগার",
    bookReservation: "বই সংরক্ষণ",
    budgetReport: "বাজেট রিপোর্ট",
    paymentHistory: "পেমেন্ট ইতিহাস",
    noResults: "কোনো ফলাফল নেই",
    language: "ভাষা",
    backgroundColor: "পটভূমির রঙ",
    saveChanges: "পরিবর্তন সংরক্ষণ",
    profileSettings: "প্রোফাইল সেটিংস",
    security: "নিরাপত্তা",
    notifications: "বিজ্ঞপ্তি",
    schoolSettings: "স্কুল সেটিংস",
    monday: "সোমবার",
    tuesday: "মঙ্গলবার",
    wednesday: "বুধবার",
    thursday: "বৃহস্পতিবার",
    friday: "শুক্রবার",
    saturday: "শনিবার",
    sunday: "রবিবার",
    selectClass: "ক্লাস নির্বাচন",
    selectDay: "দিন নির্বাচন",
    selectExam: "পরীক্ষা নির্বাচন",
    selectSubject: "বিষয় নির্বাচন",
    period: "পিরিয়ড",
    saveAttendance: "উপস্থিতি সংরক্ষণ",
    saveGrades: "গ্রেড সংরক্ষণ",
    attendanceRate: "উপস্থিতির হার",
    studentName: "শিক্ষার্থীর নাম",
    rollNo: "রোল নং.",
    age: "বয়স",
    department: "বিভাগ",
    qualification: "যোগ্যতা",
    contactNo: "যোগাযোগ",
    totalTeachers: "মোট শিক্ষক",
    active: "সক্রিয়",
    departments: "বিভাগসমূহ",
    linkedAccounts: "সংযুক্ত অ্যাকাউন্ট",
    notLinked: "সংযুক্ত নয়",
    examName: "পরীক্ষার নাম",
    maxMarks: "সর্বোচ্চ নম্বর",
    enterMarks: "নম্বর লিখুন",
    audience: "দর্শক",
    priorityLabel: "অগ্রাধিকার",
    high: "উচ্চ",
    medium: "মধ্যম",
    low: "নিম্ন",
    addEventBtn: "ইভেন্ট যোগ করুন",
    location: "স্থান",
    participants: "অংশগ্রহণকারী",
    eventTitle: "ইভেন্ট শিরোনাম",
    addEntry: "এন্ট্রি যোগ করুন",
    noEntriesFound: "কোনো এন্ট্রি পাওয়া যায়নি",
    weeklySchedule: "সাপ্তাহিক সময়সূচী",
    removeEntry: "এন্ট্রি সরান",
    searchStudents: "শিক্ষার্থী খুঁজুন...",
    searchTeachers: "শিক্ষক খুঁজুন...",
    searchExams: "পরীক্ষা খুঁজুন...",
    searchEvents: "ইভেন্ট খুঁজুন...",
    searchBooks: "বই খুঁজুন...",
    returnBook: "ফেরত দিন",
    issuedBooks: "ইস্যু করা বই",
    finesTab: "জরিমানা",
    reservationsTab: "সংরক্ষণ",
    physicalBooks: "ভৌতিক বই",
    digitalBooksTab: "ডিজিটাল লাইব্রেরি",
    uploadBook: "বই আপলোড",
    budgetOverview: "বাজেট সংক্ষিপ্ত",
    income: "আয়",
    expenses: "ব্যয়",
    balance: "ব্যালেন্স",
    feeReminder: "ফি স্মারক",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    transactionHistory: "লেনদেন ইতিহাস",
    uploadFile: "ফাইল আপলোড",
    noDocuments: "কোনো নথি নেই",
    routeName: "রুটের নাম",
    driverName: "চালক",
    vehicle: "যানবাহন",
    stops: "স্টপ",
    importData: "ডেটা আমদানি",
    exportData: "ডেটা রপ্তানি",
    startDate: "শুরুর তারিখ",
    endDate: "শেষ তারিখ",
    currentYear: "চলতি বছর",
    forumTitle: "ফোরামের শিরোনাম",
    newPost: "নতুন পোস্ট",
    lastActivity: "শেষ কার্যকলাপ",
    clubName: "ক্লাবের নাম",
    joinClub: "ক্লাবে যোগ দিন",
    requirements: "প্রয়োজনীয়তা",
    questionTypeLabel: "প্রশ্নের ধরন",
    mcq: "MCQ",
    shortAnswer: "সংক্ষিপ্ত উত্তর",
    essayType: "রচনা",
    addQuestion: "প্রশ্ন যোগ করুন",
    assignedTo: "নিযুক্ত",
    submittedBy: "জমা দেওয়া হয়েছে",
    gradeSubmission: "গ্রেড",
    lessonTitle: "পাঠের শিরোনাম",
    objective: "উদ্দেশ্য",
    exportCSVBtn: "CSV রপ্তানি",
    scheduleNewExam: "নতুন পরীক্ষা",
    enterGrades: "গ্রেড লিখুন",
    selectClassFirst: "উপস্থিতির জন্য ক্লাস নির্বাচন করুন",
    attendanceMark: "চিহ্নিত",
    totalFees: "মোট ফি",
    collected: "সংগ্রহ",
    pendingFees: "বকেয়া",
    payNow: "এখনই পেমেন্ট",
    configureStripe: "Stripe কনফিগার",
    uploadDate: "আপলোড তারিখ",
    fileSize: "ফাইলের আকার",
    category: "বিভাগ",
  },
  mr: {
    dashboard: "डॅशबोर्ड",
    students: "विद्यार्थी",
    teachers: "शिक्षक",
    classes: "वर्ग",
    attendance: "उपस्थिती",
    grades: "श्रेणी",
    timetable: "वेळापत्रक",
    exams: "परीक्षा",
    announcements: "घोषणा",
    library: "ग्रंथालय",
    finance: "वित्त",
    events: "कार्यक्रम",
    subjects: "विषय",
    reports: "अहवाल",
    messages: "संदेश",
    settings: "सेटिंग्ज",
    documents: "कागदपत्रे",
    transport: "वाहतूक",
    homework: "गृहपाठ",
    bulkImport: "बल्क आयात",
    academicYear: "शैक्षणिक वर्ष",
    clubs: "क्लब",
    forums: "चर्चा मंच",
    questionPaper: "प्रश्नपत्रिका",
    analytics: "विश्लेषण",
    auditLog: "ऑडिट लॉग",
    add: "जोडा",
    edit: "संपादित करा",
    delete: "हटवा",
    save: "जतन करा",
    cancel: "रद्द करा",
    search: "शोधा",
    close: "बंद करा",
    submit: "सादर करा",
    download: "डाउनलोड",
    upload: "अपलोड",
    all: "सर्व",
    collegeStudents: "महाविद्यालय विद्यार्थी",
    collegeFaculty: "महाविद्यालय प्राध्यापक",
    parentPortal: "पालक पोर्टल",
    school: "शाळा",
    college: "महाविद्यालय",
    general: "सामान्य",
    studentsPage: "विद्यार्थी व्यवस्थापन",
    teachersPage: "शिक्षक व्यवस्थापन",
    classesPage: "वर्ग व्यवस्थापन",
    attendancePage: "उपस्थिती ट्रॅकर",
    gradesPage: "श्रेणी व्यवस्थापन",
    timetablePage: "वेळापत्रक",
    examsPage: "परीक्षा",
    announcementsPage: "घोषणा",
    libraryPage: "ग्रंथालय",
    financePage: "वित्त",
    eventsPage: "कार्यक्रम",
    subjectsPage: "विषय",
    reportsPage: "अहवाल",
    messagesPage: "संदेश",
    settingsPage: "सेटिंग्ज",
    documentsPage: "कागदपत्रे",
    transportPage: "वाहतूक व्यवस्थापन",
    homeworkPage: "गृहपाठ",
    analyticsPage: "विश्लेषण डॅशबोर्ड",
    auditLogPage: "ऑडिट लॉग",
    clubsPage: "क्लब",
    forumsPage: "चर्चा मंच",
    addStudent: "विद्यार्थी जोडा",
    addTeacher: "शिक्षक जोडा",
    addClass: "वर्ग जोडा",
    addEvent: "कार्यक्रम जोडा",
    addSubject: "विषय जोडा",
    markAttendance: "उपस्थिती नोंदवा",
    addGrade: "श्रेणी जोडा",
    addExam: "परीक्षा जोडा",
    addAnnouncement: "घोषणा जोडा",
    compose: "लिहा",
    inbox: "इनबॉक्स",
    sent: "पाठवलेले",
    starred: "तारांकित",
    trash: "ट्रॅश",
    present: "उपस्थित",
    absent: "अनुपस्थित",
    pending: "प्रलंबित",
    paid: "भरले",
    unpaid: "न भरलेले",
    payOnline: "ऑनलाइन पेमेंट",
    viewDetails: "तपशील",
    printReport: "अहवाल प्रिंट",
    exportCSV: "CSV निर्यात",
    name: "नाव",
    class: "वर्ग",
    section: "विभाग",
    subject: "विषय",
    date: "तारीख",
    status: "स्थिती",
    actions: "क्रिया",
    total: "एकूण",
    fee: "शुल्क",
    amount: "रक्कम",
    type: "प्रकार",
    description: "वर्णन",
    phone: "फोन",
    email: "ईमेल",
    address: "पत्ता",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    role: "भूमिका",
    password: "पासवर्ड",
    confirm: "पुष्टी करा",
    update: "अद्यतन",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    login: "लॉगिन",
    signup: "साइन अप",
    welcome: "स्वागत",
    loading: "लोड होत आहे...",
    noData: "डेटा नाही",
    filter: "फिल्टर",
    reset: "रीसेट",
    print: "प्रिंट",
    share: "शेअर",
    approve: "मंजूर करा",
    reject: "नाकारा",
    reserve: "राखीव",
    return: "परत करा",
    fine: "दंड",
    available: "उपलब्ध",
    checkedOut: "नेले आहे",
    reserved: "राखीव",
    overdue: "मुदत संपली",
    totalClasses: "एकूण वर्ग",
    totalStudents: "एकूण विद्यार्थी",
    avgClassSize: "सरासरी वर्ग आकार",
    classTeacher: "वर्ग शिक्षक",
    room: "खोली",
    editClass: "वर्ग संपादित करा",
    addNewClass: "नवीन वर्ग जोडा",
    searchClasses: "वर्ग शोधा...",
    noClassesFound: "कोणताही वर्ग सापडला नाही",
    deleteClass: "वर्ग हटवा",
    activeClasses: "वर्ग सक्रिय",
    gradeName: "ग्रेड/वर्ग नाव",
    numberOfStudents: "विद्यार्थ्यांची संख्या",
    roomNumber: "खोली क्रमांक",
    selectTeacher: "शिक्षक निवडा",
    quickActions: "त्वरित क्रिया",
    studentEnrollmentTrend: "विद्यार्थी प्रवेश प्रवृत्ती",
    monthlyPerformanceScore: "मासिक कामगिरी गुण",
    topStudents: "शीर्ष विद्यार्थी",
    recentActivity: "अलीकडील क्रियाकलाप",
    attendanceOverview: "उपस्थिती आढावा",
    welcomeBack: "परत स्वागत! येथे तुमच्या शाळेचे विहंगावलोकन.",
    rank: "क्रमांक",
    average: "सरासरी",
    viewAll: "सर्व पहा",
    scheduleExam: "परीक्षा वेळापत्रक",
    postAnnouncement: "घोषणा पोस्ट",
    feeCollection: "शुल्क संकलन",
    viewReports: "अहवाल पहा",
    myTimetable: "माझे वेळापत्रक",
    leaveApplication: "रजा अर्ज",
    attendanceSummary: "उपस्थिती सारांश",
    reportCard: "अहवाल पत्रिका",
    feeHistory: "शुल्क इतिहास",
    gpaCalculator: "GPA कॅल्क्युलेटर",
    digitalLibrary: "डिजिटल ग्रंथालय",
    bookReservation: "पुस्तक राखीव",
    budgetReport: "अर्थसंकल्प अहवाल",
    paymentHistory: "पेमेंट इतिहास",
    noResults: "परिणाम नाही",
    language: "भाषा",
    backgroundColor: "पार्श्वभूमी रंग",
    saveChanges: "बदल जतन करा",
    profileSettings: "प्रोफाइल सेटिंग्ज",
    security: "सुरक्षा",
    notifications: "सूचना",
    schoolSettings: "शाळा सेटिंग्ज",
    monday: "सोमवार",
    tuesday: "मंगळवार",
    wednesday: "बुधवार",
    thursday: "गुरुवार",
    friday: "शुक्रवार",
    saturday: "शनिवार",
    sunday: "रविवार",
    selectClass: "वर्ग निवडा",
    selectDay: "दिवस निवडा",
    selectExam: "परीक्षा निवडा",
    selectSubject: "विषय निवडा",
    period: "तास",
    saveAttendance: "उपस्थिती सेव्ह",
    saveGrades: "गुण सेव्ह",
    attendanceRate: "उपस्थितीचा दर",
    studentName: "विद्यार्थी नाव",
    rollNo: "रोल नं.",
    age: "वय",
    department: "विभाग",
    qualification: "पात्रता",
    contactNo: "संपर्क",
    totalTeachers: "एकूण शिक्षक",
    active: "सक्रिय",
    departments: "विभाग",
    linkedAccounts: "लिंक केलेले खाते",
    notLinked: "लिंक नाही",
    examName: "परीक्षेचे नाव",
    maxMarks: "जास्तीत जास्त गुण",
    enterMarks: "गुण प्रविष्ट करा",
    audience: "प्रेक्षक",
    priorityLabel: "प्राधान्य",
    high: "उच्च",
    medium: "मध्यम",
    low: "कमी",
    addEventBtn: "कार्यक्रम जोडा",
    location: "ठिकाण",
    participants: "सहभागी",
    eventTitle: "कार्यक्रम शीर्षक",
    addEntry: "नोंद जोडा",
    noEntriesFound: "नोंदी नाहीत",
    weeklySchedule: "साप्ताहिक वेळापत्रक",
    removeEntry: "नोंद काढा",
    searchStudents: "विद्यार्थी शोधा...",
    searchTeachers: "शिक्षक शोधा...",
    searchExams: "परीक्षा शोधा...",
    searchEvents: "कार्यक्रम शोधा...",
    searchBooks: "पुस्तक शोधा...",
    returnBook: "परत करा",
    issuedBooks: "दिलेली पुस्तके",
    finesTab: "दंड",
    reservationsTab: "आरक्षण",
    physicalBooks: "भौतिक पुस्तके",
    digitalBooksTab: "डिजिटल ग्रंथालय",
    uploadBook: "पुस्तक अपलोड",
    budgetOverview: "अर्थसंकल्प आढावा",
    income: "उत्पन्न",
    expenses: "खर्च",
    balance: "शिल्लक",
    feeReminder: "शुल्क स्मरण",
    paymentMethod: "पेमेंट पद्धत",
    transactionHistory: "व्यवहार इतिहास",
    uploadFile: "फाइल अपलोड",
    noDocuments: "कोणतेही दस्तऐवज नाही",
    routeName: "मार्ग नाव",
    driverName: "चालक",
    vehicle: "वाहन",
    stops: "थांबे",
    importData: "डेटा आयात",
    exportData: "डेटा निर्यात",
    startDate: "प्रारंभ तारीख",
    endDate: "समाप्ती तारीख",
    currentYear: "चालू वर्ष",
    forumTitle: "मंच शीर्षक",
    newPost: "नवीन पोस्ट",
    lastActivity: "शेवटची क्रिया",
    clubName: "क्लबचे नाव",
    joinClub: "क्लब जॉइन",
    requirements: "आवश्यकता",
    questionTypeLabel: "प्रश्न प्रकार",
    mcq: "MCQ",
    shortAnswer: "लहान उत्तर",
    essayType: "निबंध",
    addQuestion: "प्रश्न जोडा",
    assignedTo: "नियुक्त केले",
    submittedBy: "सादर केले",
    gradeSubmission: "ग्रेड",
    lessonTitle: "धड्याचे शीर्षक",
    objective: "उद्दिष्ट",
    exportCSVBtn: "CSV निर्यात",
    scheduleNewExam: "नवीन परीक्षा",
    enterGrades: "गुण प्रविष्ट करा",
    selectClassFirst: "उपस्थितीसाठी वर्ग निवडा",
    attendanceMark: "खूण",
    totalFees: "एकूण शुल्क",
    collected: "जमा",
    pendingFees: "थकबाकी",
    payNow: "आत्ता भरा",
    configureStripe: "Stripe कॉन्फिगर",
    uploadDate: "अपलोड तारीख",
    fileSize: "फाइल आकार",
    category: "श्रेणी",
  },
  gu: {
    dashboard: "ડૅશબોર્ડ",
    students: "વિદ્યાર્થીઓ",
    teachers: "શિક્ષકો",
    classes: "વર્ગો",
    attendance: "હાજરી",
    grades: "ગ્રેડ",
    timetable: "સમયપત્રક",
    exams: "પરીક્ષા",
    announcements: "જાહેરાત",
    library: "પુસ્તકાલય",
    finance: "નાણાં",
    events: "કાર્યક્રમ",
    subjects: "વિષય",
    reports: "અહેવાલ",
    messages: "સંદેશ",
    settings: "સેટિંગ્સ",
    documents: "દસ્તાવેજ",
    transport: "પરિવહન",
    homework: "ગૃહકાર્ય",
    bulkImport: "બલ્ક આયાત",
    academicYear: "શૈક્ષણિક વર્ષ",
    clubs: "ક્લબ",
    forums: "ચર્ચા મંચ",
    questionPaper: "પ્રશ્નપત્ર",
    analytics: "વિશ્લેષણ",
    auditLog: "ઑડિટ લૉગ",
    add: "ઉમેરો",
    edit: "સંપાદિત કરો",
    delete: "કાઢો",
    save: "સાચવો",
    cancel: "રદ કરો",
    search: "શોધો",
    close: "બંધ",
    submit: "સબમિટ",
    download: "ડાઉનલોડ",
    upload: "અપલોડ",
    all: "બધા",
    collegeStudents: "કૉલેજ વિદ્યાર્થીઓ",
    collegeFaculty: "કૉલેજ ફૅકલ્ટી",
    parentPortal: "વાલી પોર્ટલ",
    school: "શાળા",
    college: "કૉલેજ",
    general: "સામાન્ય",
    studentsPage: "વિદ્યાર્થી વ્યવસ્થાપન",
    teachersPage: "શિક્ષક વ્યવસ્થાપન",
    classesPage: "વર્ગ વ્યવસ્થાપન",
    attendancePage: "હાજરી ટ્રૅકર",
    gradesPage: "ગ્રેડ વ્યવસ્થાપન",
    timetablePage: "સમયપત્રક",
    examsPage: "પરીક્ષા",
    announcementsPage: "જાહેરાત",
    libraryPage: "પુસ્તકાલય",
    financePage: "નાણાં",
    eventsPage: "કાર્યક્રમ",
    subjectsPage: "વિષય",
    reportsPage: "અહેવાલ",
    messagesPage: "સંદેશ",
    settingsPage: "સેટિંગ્સ",
    documentsPage: "દસ્તાવેજ",
    transportPage: "પરિવહન વ્યવસ્થાપન",
    homeworkPage: "ગૃહકાર્ય",
    analyticsPage: "વિશ્લેષણ ડૅશબોર્ડ",
    auditLogPage: "ઑડિટ લૉગ",
    clubsPage: "ક્લબ",
    forumsPage: "ચર્ચા મંચ",
    addStudent: "વિદ્યાર્થી ઉમેરો",
    addTeacher: "શિક્ષક ઉમેરો",
    addClass: "વર્ગ ઉમેરો",
    addEvent: "કાર્યક્રમ ઉમેરો",
    addSubject: "વિષય ઉમેરો",
    markAttendance: "હાજરી નોંધો",
    addGrade: "ગ્રેડ ઉમેરો",
    addExam: "પરીક્ષા ઉમેરો",
    addAnnouncement: "જાહેરાત ઉમેરો",
    compose: "લખો",
    inbox: "ઇનબૉક્સ",
    sent: "મોકલ્યા",
    starred: "તારાંકિત",
    trash: "ટ્રૅશ",
    present: "હાજર",
    absent: "ગેરહાજર",
    pending: "બાકી",
    paid: "ચૂકવ્યું",
    unpaid: "ચૂકવ્યું નથી",
    payOnline: "ઑનલાઇન પૅ",
    viewDetails: "વિગત",
    printReport: "અહેવાલ છાપો",
    exportCSV: "CSV નિકાસ",
    name: "નામ",
    class: "વર્ગ",
    section: "વિભાગ",
    subject: "વિષય",
    date: "તારીખ",
    status: "સ્થિતિ",
    actions: "ક્રિયા",
    total: "કુલ",
    fee: "ફી",
    amount: "રકમ",
    type: "પ્રકાર",
    description: "વર્ણન",
    phone: "ફોન",
    email: "ઈમેઇલ",
    address: "સરનામું",
    gender: "લિંગ",
    male: "પુરુષ",
    female: "સ્ત્રી",
    role: "ભૂમિકા",
    password: "પાસવર્ડ",
    confirm: "ખાતરી",
    update: "અપડેટ",
    profile: "પ્રોફાઇલ",
    logout: "લૉગ આઉટ",
    login: "લૉગઇન",
    signup: "સાઇન અપ",
    welcome: "સ્વાગત",
    loading: "લોડ થઈ રહ્યું છે...",
    noData: "કોઈ ડેટા નથી",
    filter: "ફિલ્ટર",
    reset: "રીસેટ",
    print: "છાપો",
    share: "શૅર",
    approve: "મંજૂર",
    reject: "નકારો",
    reserve: "રિઝર્વ",
    return: "પરત",
    fine: "દંડ",
    available: "ઉપલબ્ધ",
    checkedOut: "લઈ ગયા",
    reserved: "રિઝર્વ",
    overdue: "મુદત વીતી",
    totalClasses: "કુલ વર્ગો",
    totalStudents: "કુલ વિદ્યાર્થીઓ",
    avgClassSize: "સરેરાશ વર્ગ આકાર",
    classTeacher: "વર્ગ શિક્ષક",
    room: "ઓરડો",
    editClass: "વર્ગ સંપાદિત કરો",
    addNewClass: "નવો વર્ગ ઉમેરો",
    searchClasses: "વર્ગ શોધો...",
    noClassesFound: "કોઈ વર્ગ મળ્યો નહીં",
    deleteClass: "વર્ગ કાઢો",
    activeClasses: "વર્ગ સક્રિય",
    gradeName: "ગ્રેડ/વર્ગ નામ",
    numberOfStudents: "વિદ્યાર્થીઓની સંખ્યા",
    roomNumber: "ઓરડો નંબર",
    selectTeacher: "શિક્ષક પસંદ કરો",
    quickActions: "ઝડપી ક્રિયાઓ",
    studentEnrollmentTrend: "વિદ્યાર્થી નોંધણી વલણ",
    monthlyPerformanceScore: "માસિક પ્રદર્શન સ્કોર",
    topStudents: "ટોચના વિદ્યાર્થીઓ",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",
    attendanceOverview: "હાજરી અવલોકન",
    welcomeBack: "પાછા સ્વાગત! અહીં તમારી શાળાનો સારાંશ.",
    rank: "ક્રમ",
    average: "સરેરાશ",
    viewAll: "બધા જુઓ",
    scheduleExam: "પરીક્ષા સુનિશ્ચિત",
    postAnnouncement: "જાહેરાત પોસ્ટ",
    feeCollection: "ફી સંગ્રહ",
    viewReports: "રિપોર્ટ જુઓ",
    myTimetable: "મારું સમયપત્રક",
    leaveApplication: "રજા અરજી",
    attendanceSummary: "હાજરી સારાંશ",
    reportCard: "રિપોર્ટ કાર્ડ",
    feeHistory: "ફી ઇતિહાસ",
    gpaCalculator: "GPA કૅલ્ક્યુલેટર",
    digitalLibrary: "ડિજિટલ પુસ્તકાલય",
    bookReservation: "પુસ્તક આરક્ષણ",
    budgetReport: "બજેટ રિપોર્ટ",
    paymentHistory: "ચુકવણી ઇતિહાસ",
    noResults: "કોઈ પરિણામ નથી",
    language: "ભાષા",
    backgroundColor: "પૃષ્ઠભૂ રંગ",
    saveChanges: "ફેરફારો સાચવો",
    profileSettings: "પ્રોફાઇલ સેટિંગ્સ",
    security: "સુરક્ષા",
    notifications: "સૂચનાઓ",
    schoolSettings: "શાળા સેટિંગ્સ",
    monday: "સોમવાર",
    tuesday: "મંગળવાર",
    wednesday: "બુધવાર",
    thursday: "ગુરુવાર",
    friday: "શુક્રવાર",
    saturday: "શનિવાર",
    sunday: "રવિવાર",
    selectClass: "વર્ગ પસંદ",
    selectDay: "દિવસ પસંદ",
    selectExam: "પરીક્ષા પસંદ",
    selectSubject: "વિષય પસંદ",
    period: "સત્ર",
    saveAttendance: "હાજરી સાચવો",
    saveGrades: "ગ્રેડ સાચવો",
    attendanceRate: "હાજરી દર",
    studentName: "વિદ્યાર્થી નામ",
    rollNo: "રોલ નં.",
    age: "ઉંમર",
    department: "વિભાગ",
    qualification: "લાયકાત",
    contactNo: "સંપર્ક",
    totalTeachers: "કુલ શિક્ષકો",
    active: "સક્રિય",
    departments: "વિભાગો",
    linkedAccounts: "લિંક્ડ એકાઉન્ટ",
    notLinked: "લિંક નથી",
    examName: "પરીક્ષા નામ",
    maxMarks: "મહત્તમ ગુણ",
    enterMarks: "ગુણ દાખલ",
    audience: "પ્રેક્ષકો",
    priorityLabel: "પ્રાથમિકતા",
    high: "ઊંચી",
    medium: "મધ્ય",
    low: "નીચી",
    addEventBtn: "ઈવેન્ટ ઉમેરો",
    location: "સ્થળ",
    participants: "સહભાગીઓ",
    eventTitle: "ઈવેન્ટ શીર્ષક",
    addEntry: "પ્રવેશ ઉમેરો",
    noEntriesFound: "કોઈ પ્રવેશ નથી",
    weeklySchedule: "સાપ્તાહિક સૂચિ",
    removeEntry: "પ્રવેશ કાઢો",
    searchStudents: "વિદ્યાર્થી શોધો...",
    searchTeachers: "શિક્ષક શોધો...",
    searchExams: "પરીક્ષા શોધો...",
    searchEvents: "ઈવેન્ટ શોધો...",
    searchBooks: "પુસ્તક શોધો...",
    returnBook: "પરત",
    issuedBooks: "ઈસ્યુ કરેલ પુસ્તકો",
    finesTab: "દંડ",
    reservationsTab: "આરક્ષણ",
    physicalBooks: "ભૌતિક પુસ્તકો",
    digitalBooksTab: "ડિજિટલ પુસ્તકાલય",
    uploadBook: "પુસ્તક અપલોડ",
    budgetOverview: "બજેટ સારાંશ",
    income: "આવક",
    expenses: "ખર્ચ",
    balance: "બેલેન્સ",
    feeReminder: "ફી રીમાઇન્ડર",
    paymentMethod: "ચૂકવણી પદ્ધતિ",
    transactionHistory: "વ્યવહાર ઇતિહાસ",
    uploadFile: "ફાઇલ અપલોડ",
    noDocuments: "કોઈ દસ્તાવેજ નથી",
    routeName: "રૂટ નામ",
    driverName: "ડ્રાઈવર",
    vehicle: "વાહન",
    stops: "સ્ટોપ",
    importData: "ડેટા આયાત",
    exportData: "ડેટા નિકાસ",
    startDate: "પ્રારંભ તારીખ",
    endDate: "સમાપ્તિ તારીખ",
    currentYear: "ચાલુ વર્ષ",
    forumTitle: "ફોરમ શીર્ષક",
    newPost: "નવી પોસ્ટ",
    lastActivity: "છેલ્લી પ્રવૃત્તિ",
    clubName: "ક્લબ નામ",
    joinClub: "ક્લબ જોડાઓ",
    requirements: "જરૂરિયાતો",
    questionTypeLabel: "પ્રશ્ન પ્રકાર",
    mcq: "MCQ",
    shortAnswer: "ટૂંકો જવાબ",
    essayType: "નિબંધ",
    addQuestion: "પ્રશ્ન ઉમેરો",
    assignedTo: "સોંપ્યું",
    submittedBy: "સબમિટ",
    gradeSubmission: "ગ્રેડ",
    lessonTitle: "પ્રકરણ શીર્ષક",
    objective: "ઉદ્દેશ",
    exportCSVBtn: "CSV નિકાસ",
    scheduleNewExam: "નવી પરીક્ષા",
    enterGrades: "ગ્રેડ દાખલ",
    selectClassFirst: "હાજરી માટે વર્ગ પસંદ",
    attendanceMark: "ચિહ્ન",
    totalFees: "કુલ ફી",
    collected: "એકત્ર",
    pendingFees: "બાકી",
    payNow: "હવે ચૂકવો",
    configureStripe: "Stripe કૉન્ફિગ",
    uploadDate: "અપલોડ તારીખ",
    fileSize: "ફાઇલ સાઇઝ",
    category: "શ્રેણી",
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("edumanage_language");
    return (stored as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("edumanage_language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations.en[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
