/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'title' : string,
  'content' : string,
  'date' : Time,
  'targetAudience' : Array<string>,
}
export type AnnouncementId = bigint;
export interface Attendance {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Time,
  'classId' : ClassId,
}
export type AttendanceId = bigint;
export type AttendanceStatus = { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null };
export type ClassId = bigint;
export interface Exam {
  'id' : ExamId,
  'date' : Time,
  'name' : string,
  'classId' : ClassId,
  'subjectId' : SubjectId,
  'maxMarks' : bigint,
}
export type ExamId = bigint;
export interface Grade {
  'id' : GradeId,
  'totalMarks' : bigint,
  'studentId' : StudentId,
  'marksObtained' : bigint,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'percentage' : bigint,
}
export type GradeId = bigint;
export interface SchoolClass {
  'id' : ClassId,
  'name' : string,
  'section' : string,
  'studentIds' : Array<StudentId>,
  'subjectIds' : Array<SubjectId>,
  'teacherId' : TeacherId,
}
export interface Student {
  'id' : StudentId,
  'age' : bigint,
  'parentContact' : string,
  'userId' : Principal,
  'name' : string,
  'classId' : ClassId,
  'rollNumber' : bigint,
  'address' : string,
}
export type StudentId = bigint;
export interface Subject {
  'id' : SubjectId,
  'name' : string,
  'classId' : ClassId,
  'teacherId' : TeacherId,
}
export type SubjectId = bigint;
export interface Teacher {
  'id' : TeacherId,
  'contact' : string,
  'subjectSpecialization' : Array<string>,
  'userId' : Principal,
  'name' : string,
  'qualification' : string,
}
export type TeacherId = bigint;
export type Time = bigint;
export interface TimetableEntry {
  'id' : TimetableEntryId,
  'day' : string,
  'period' : string,
  'time' : string,
  'classId' : ClassId,
  'subjectId' : SubjectId,
  'teacherId' : TeacherId,
}
export type TimetableEntryId = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'entityId' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, string, Time, Array<string>],
    AnnouncementId
  >,
  'createClass' : ActorMethod<
    [string, string, TeacherId, Array<SubjectId>],
    ClassId
  >,
  'createExam' : ActorMethod<
    [string, SubjectId, Time, ClassId, bigint],
    ExamId
  >,
  'createStudent' : ActorMethod<
    [string, bigint, ClassId, bigint, string, string, Principal],
    StudentId
  >,
  'createSubject' : ActorMethod<[string, ClassId, TeacherId], SubjectId>,
  'createTeacher' : ActorMethod<
    [string, Array<string>, string, string, Principal],
    TeacherId
  >,
  'createTimetableEntry' : ActorMethod<
    [ClassId, string, string, SubjectId, TeacherId, string],
    TimetableEntryId
  >,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllAttendance' : ActorMethod<[], Array<Attendance>>,
  'getAllClasses' : ActorMethod<[], Array<SchoolClass>>,
  'getAllExams' : ActorMethod<[], Array<Exam>>,
  'getAllGrades' : ActorMethod<[], Array<Grade>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAllTimetableEntries' : ActorMethod<[], Array<TimetableEntry>>,
  'getAnnouncement' : ActorMethod<[AnnouncementId], Announcement>,
  'getAttendance' : ActorMethod<[AttendanceId], Attendance>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[ClassId], SchoolClass>,
  'getExam' : ActorMethod<[ExamId], Exam>,
  'getGrade' : ActorMethod<[GradeId], Grade>,
  'getMyAttendance' : ActorMethod<[], Array<Attendance>>,
  'getMyGrades' : ActorMethod<[], Array<Grade>>,
  'getMyStudentProfile' : ActorMethod<[], [] | [Student]>,
  'getStudent' : ActorMethod<[StudentId], Student>,
  'getSubject' : ActorMethod<[SubjectId], Subject>,
  'getTeacher' : ActorMethod<[TeacherId], Teacher>,
  'getTimetableEntry' : ActorMethod<[TimetableEntryId], TimetableEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<
    [StudentId, ClassId, Time, AttendanceStatus],
    AttendanceId
  >,
  'recordGrade' : ActorMethod<
    [StudentId, SubjectId, ExamId, bigint, bigint],
    GradeId
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];