/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AnnouncementId = IDL.Nat;
export const TeacherId = IDL.Nat;
export const SubjectId = IDL.Nat;
export const ClassId = IDL.Nat;
export const ExamId = IDL.Nat;
export const StudentId = IDL.Nat;
export const TimetableEntryId = IDL.Nat;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'targetAudience' : IDL.Vec(IDL.Text),
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : StudentId,
  'date' : Time,
  'classId' : ClassId,
});
export const SchoolClass = IDL.Record({
  'id' : ClassId,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'studentIds' : IDL.Vec(StudentId),
  'subjectIds' : IDL.Vec(SubjectId),
  'teacherId' : TeacherId,
});
export const Exam = IDL.Record({
  'id' : ExamId,
  'date' : Time,
  'name' : IDL.Text,
  'classId' : ClassId,
  'subjectId' : SubjectId,
  'maxMarks' : IDL.Nat,
});
export const GradeId = IDL.Nat;
export const Grade = IDL.Record({
  'id' : GradeId,
  'totalMarks' : IDL.Nat,
  'studentId' : StudentId,
  'marksObtained' : IDL.Nat,
  'subjectId' : SubjectId,
  'examId' : ExamId,
  'percentage' : IDL.Nat,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'age' : IDL.Nat,
  'parentContact' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'classId' : ClassId,
  'rollNumber' : IDL.Nat,
  'address' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'name' : IDL.Text,
  'classId' : ClassId,
  'teacherId' : TeacherId,
});
export const Teacher = IDL.Record({
  'id' : TeacherId,
  'contact' : IDL.Text,
  'subjectSpecialization' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'qualification' : IDL.Text,
});
export const TimetableEntry = IDL.Record({
  'id' : TimetableEntryId,
  'day' : IDL.Text,
  'period' : IDL.Text,
  'time' : IDL.Text,
  'classId' : ClassId,
  'subjectId' : SubjectId,
  'teacherId' : TeacherId,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'entityId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Text)],
      [AnnouncementId],
      [],
    ),
  'createClass' : IDL.Func(
      [IDL.Text, IDL.Text, TeacherId, IDL.Vec(SubjectId)],
      [ClassId],
      [],
    ),
  'createExam' : IDL.Func(
      [IDL.Text, SubjectId, Time, ClassId, IDL.Nat],
      [ExamId],
      [],
    ),
  'createStudent' : IDL.Func(
      [IDL.Text, IDL.Nat, ClassId, IDL.Nat, IDL.Text, IDL.Text, IDL.Principal],
      [StudentId],
      [],
    ),
  'createSubject' : IDL.Func([IDL.Text, ClassId, TeacherId], [SubjectId], []),
  'createTeacher' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Principal],
      [TeacherId],
      [],
    ),
  'createTimetableEntry' : IDL.Func(
      [ClassId, IDL.Text, IDL.Text, SubjectId, TeacherId, IDL.Text],
      [TimetableEntryId],
      [],
    ),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getAllClasses' : IDL.Func([], [IDL.Vec(SchoolClass)], ['query']),
  'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
  'getAllGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAllTimetableEntries' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
  'getAnnouncement' : IDL.Func([AnnouncementId], [Announcement], ['query']),
  'getAttendance' : IDL.Func([AttendanceId], [Attendance], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([ClassId], [SchoolClass], ['query']),
  'getExam' : IDL.Func([ExamId], [Exam], ['query']),
  'getGrade' : IDL.Func([GradeId], [Grade], ['query']),
  'getMyAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getMyGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
  'getMyStudentProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'getStudent' : IDL.Func([StudentId], [Student], ['query']),
  'getSubject' : IDL.Func([SubjectId], [Subject], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
  'getTimetableEntry' : IDL.Func(
      [TimetableEntryId],
      [TimetableEntry],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func(
      [StudentId, ClassId, Time, AttendanceStatus],
      [AttendanceId],
      [],
    ),
  'recordGrade' : IDL.Func(
      [StudentId, SubjectId, ExamId, IDL.Nat, IDL.Nat],
      [GradeId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AnnouncementId = IDL.Nat;
  const TeacherId = IDL.Nat;
  const SubjectId = IDL.Nat;
  const ClassId = IDL.Nat;
  const ExamId = IDL.Nat;
  const StudentId = IDL.Nat;
  const TimetableEntryId = IDL.Nat;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'targetAudience' : IDL.Vec(IDL.Text),
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : StudentId,
    'date' : Time,
    'classId' : ClassId,
  });
  const SchoolClass = IDL.Record({
    'id' : ClassId,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'studentIds' : IDL.Vec(StudentId),
    'subjectIds' : IDL.Vec(SubjectId),
    'teacherId' : TeacherId,
  });
  const Exam = IDL.Record({
    'id' : ExamId,
    'date' : Time,
    'name' : IDL.Text,
    'classId' : ClassId,
    'subjectId' : SubjectId,
    'maxMarks' : IDL.Nat,
  });
  const GradeId = IDL.Nat;
  const Grade = IDL.Record({
    'id' : GradeId,
    'totalMarks' : IDL.Nat,
    'studentId' : StudentId,
    'marksObtained' : IDL.Nat,
    'subjectId' : SubjectId,
    'examId' : ExamId,
    'percentage' : IDL.Nat,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'age' : IDL.Nat,
    'parentContact' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'classId' : ClassId,
    'rollNumber' : IDL.Nat,
    'address' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'name' : IDL.Text,
    'classId' : ClassId,
    'teacherId' : TeacherId,
  });
  const Teacher = IDL.Record({
    'id' : TeacherId,
    'contact' : IDL.Text,
    'subjectSpecialization' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'qualification' : IDL.Text,
  });
  const TimetableEntry = IDL.Record({
    'id' : TimetableEntryId,
    'day' : IDL.Text,
    'period' : IDL.Text,
    'time' : IDL.Text,
    'classId' : ClassId,
    'subjectId' : SubjectId,
    'teacherId' : TeacherId,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'entityId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Vec(IDL.Text)],
        [AnnouncementId],
        [],
      ),
    'createClass' : IDL.Func(
        [IDL.Text, IDL.Text, TeacherId, IDL.Vec(SubjectId)],
        [ClassId],
        [],
      ),
    'createExam' : IDL.Func(
        [IDL.Text, SubjectId, Time, ClassId, IDL.Nat],
        [ExamId],
        [],
      ),
    'createStudent' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          ClassId,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Principal,
        ],
        [StudentId],
        [],
      ),
    'createSubject' : IDL.Func([IDL.Text, ClassId, TeacherId], [SubjectId], []),
    'createTeacher' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Principal],
        [TeacherId],
        [],
      ),
    'createTimetableEntry' : IDL.Func(
        [ClassId, IDL.Text, IDL.Text, SubjectId, TeacherId, IDL.Text],
        [TimetableEntryId],
        [],
      ),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getAllClasses' : IDL.Func([], [IDL.Vec(SchoolClass)], ['query']),
    'getAllExams' : IDL.Func([], [IDL.Vec(Exam)], ['query']),
    'getAllGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAllTimetableEntries' : IDL.Func(
        [],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
    'getAnnouncement' : IDL.Func([AnnouncementId], [Announcement], ['query']),
    'getAttendance' : IDL.Func([AttendanceId], [Attendance], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([ClassId], [SchoolClass], ['query']),
    'getExam' : IDL.Func([ExamId], [Exam], ['query']),
    'getGrade' : IDL.Func([GradeId], [Grade], ['query']),
    'getMyAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getMyGrades' : IDL.Func([], [IDL.Vec(Grade)], ['query']),
    'getMyStudentProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'getStudent' : IDL.Func([StudentId], [Student], ['query']),
    'getSubject' : IDL.Func([SubjectId], [Subject], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [Teacher], ['query']),
    'getTimetableEntry' : IDL.Func(
        [TimetableEntryId],
        [TimetableEntry],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func(
        [StudentId, ClassId, Time, AttendanceStatus],
        [AttendanceId],
        [],
      ),
    'recordGrade' : IDL.Func(
        [StudentId, SubjectId, ExamId, IDL.Nat, IDL.Nat],
        [GradeId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };